import type { LoginPageContentProps } from './LoginPage.content.types';

export type LoginPageStepContentProps = Pick<
  LoginPageContentProps,
  | 'availableCount'
  | 'connectedAccounts'
  | 'email'
  | 'error'
  | 'handleAccountSelect'
  | 'handleDisconnectAccount'
  | 'handleDisconnectAllAccounts'
  | 'handleConsentApprove'
  | 'handleConsentCancel'
  | 'handleIdentifierSubmit'
  | 'handleMfaSubmit'
  | 'handlePasswordSubmit'
  | 'handleUseAnotherAccount'
  | 'hasRecovery'
  | 'hasTotp'
  | 'hasWebAuthn'
  | 'identifierSubmitting'
  | 'loading'
  | 'mfaMethod'
  | 'oauthRequest'
  | 'password'
  | 'recoveryCode'
  | 'resetToIdentifier'
  | 'setEmail'
  | 'setError'
  | 'setMfaMethod'
  | 'setPassword'
  | 'setRecoveryCode'
  | 'setTotpCode'
  | 'step'
  | 'totpCode'
>;
