import type { SecretResult } from './WorkspaceServiceAccounts.helpers';

export type WorkspaceServiceAccountsDialogsProps = {
  createOpen: boolean;
  setCreateOpen: (open: boolean) => void;
  createName: string;
  setCreateName: (value: string) => void;
  createDescription: string;
  setCreateDescription: (value: string) => void;
  createRole: string;
  setCreateRole: (value: string) => void;
  createError: string | null;
  busyAction: string | null;
  onCreate: () => void;
  onClearCreate: () => void;
  clientDialogOpen: boolean;
  setClientDialogOpen: (open: boolean) => void;
  clientName: string;
  setClientName: (value: string) => void;
  clientScopes: string;
  setClientScopes: (value: string) => void;
  clientAudiences: string;
  setClientAudiences: (value: string) => void;
  clientResources: string;
  setClientResources: (value: string) => void;
  clientRequiredAcr: string;
  setClientRequiredAcr: (value: string) => void;
  clientAssertionRequired: boolean;
  setClientAssertionRequired: (value: boolean) => void;
  clientAssertionJwk: string;
  setClientAssertionJwk: (value: string) => void;
  clientError: string | null;
  onCreateClient: () => void;
  onClearClient: () => void;
  attachDialogOpen: boolean;
  setAttachDialogOpen: (open: boolean) => void;
  attachClientId: string;
  setAttachClientId: (value: string) => void;
  attachError: string | null;
  onAttachClient: () => void;
  onClearAttach: () => void;
  secretResult: SecretResult | null;
  secretDialogOpen: boolean;
  setSecretDialogOpen: (open: boolean) => void;
};
