#[path = "identity.domains.auth.account_chooser.rs"]
pub mod account_chooser;
#[path = "identity.domains.auth.account_deletion.rs"]
pub mod account_deletion;
#[path = "identity.domains.auth.audit.rs"]
pub mod audit;
#[path = "identity.domains.auth.bot_guard.rs"]
pub mod bot_guard;
#[path = "identity.domains.auth.bot_response.rs"]
pub mod bot_response;
#[path = "identity.domains.auth.bot_scorer.rs"]
pub mod bot_scorer;
#[path = "identity.domains.auth.bot_signals.rs"]
pub mod bot_signals;
#[path = "identity.domains.auth.challenge_proof.rs"]
pub mod challenge_proof;
#[path = "identity.domains.auth.credential_stuffing.rs"]
pub mod credential_stuffing;
#[path = "identity.domains.auth.data_export.rs"]
pub mod data_export;
#[path = "identity.domains.auth.db.rs"]
pub mod db;
#[path = "identity.domains.auth.device_trust.rs"]
pub mod device_trust;
#[path = "identity.domains.auth.email_addresses.rs"]
pub mod email_addresses;
#[path = "identity.domains.auth.email_verification.rs"]
pub mod email_verification;
#[path = "identity.domains.auth.email_verification.change.rs"]
pub mod email_verification_change;
#[path = "identity.domains.auth.exposed_credentials.rs"]
pub mod exposed_credentials;
#[path = "identity.domains.auth.fingerprint.rs"]
pub mod fingerprint;
#[path = "identity.domains.auth.geo_intelligence.rs"]
pub(crate) mod geo_intelligence;
#[path = "identity.domains.auth.http_signals.rs"]
pub mod http_signals;
#[path = "identity.domains.auth.jwks.rs"]
pub mod jwks;
#[path = "identity.domains.auth.jwt.rs"]
pub mod jwt;
#[path = "identity.domains.auth.keys.rs"]
pub mod keys;
#[path = "identity.domains.auth.keys.local.rs"]
pub mod keys_local;
#[path = "identity.domains.auth.login_challenges.rs"]
pub mod login_challenges;
#[path = "identity.domains.auth.login.delay.rs"]
pub mod login_delay;
#[path = "identity.domains.auth.login.throttle.rs"]
pub mod login_throttle;
#[path = "identity.domains.auth.mfa.rs"]
pub mod mfa;
#[path = "identity.domains.auth.mfa.policy.rs"]
pub mod mfa_policy;
#[path = "identity.domains.auth.onboarding.rs"]
pub mod onboarding;
#[path = "identity.domains.auth.otp.mock.rs"]
pub mod otp_mock;
#[path = "identity.domains.auth.otp.provider.rs"]
pub mod otp_provider;
#[path = "identity.domains.auth.otp.twilio.rs"]
pub mod otp_twilio;
#[path = "identity.domains.auth.otp.types.rs"]
pub mod otp_types;
#[path = "identity.domains.auth.password.rs"]
pub mod password;
#[path = "identity.domains.auth.pow.rs"]
pub mod pow;
#[path = "identity.domains.auth.registration_enrollment.rs"]
pub mod registration_enrollment;
#[path = "identity.domains.auth.risk.rs"]
pub mod risk;
#[path = "identity.domains.auth.routes.rs"]
pub mod routes;
#[path = "identity.domains.auth.routes.jwks.rs"]
pub mod routes_jwks;
#[path = "identity.domains.auth.sessions.rs"]
pub mod sessions;
#[path = "identity.domains.auth.sessions.context.rs"]
pub mod sessions_context;
#[path = "identity.domains.auth.sessions.mgmt.rs"]
pub mod sessions_mgmt;
#[path = "identity.domains.auth.sso_policy.rs"]
pub mod sso_policy;
#[path = "identity.domains.auth.state.rs"]
pub mod state;
#[path = "identity.domains.auth.types.rs"]
pub mod types;
#[path = "identity.domains.auth.ua_client_hints.rs"]
pub mod ua_client_hints;
#[path = "identity.domains.auth.user_agent.rs"]
pub mod user_agent;
#[path = "identity.domains.auth.username.rs"]
pub mod username;
#[path = "identity.domains.auth.verification.rs"]
pub mod verification;
#[path = "identity.domains.auth.webauthn.rs"]
pub mod webauthn;

pub use nvbes_core::limiter::RateLimiter;
pub use nvbes_core::limiter::check_rate_limit;
pub use password::{
    generate_random_token, hash_password, hash_password_with_pepper, normalize_email, token_hash,
    unique_slug, validate_email, validate_password, verify_password, verify_password_with_pepper,
};
