use utoipa::OpenApi;
use utoipa_swagger_ui::SwaggerUi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "nvbes Account Service",
        version = "0.1.0",
        description = "Authentication, authorization, and identity management API",
        contact(name = "nvbes", url = "https://nvbes.fr"),
        license(name = "UNLICENSED"),
    ),
    servers(
        (url = "https://account.nvbes.fr", description = "Production"),
        (url = "http://localhost:8080", description = "Development"),
    ),
    tags(
        (name = "auth", description = "Authentication & sessions"),
        (name = "mfa", description = "Multi-factor authentication"),
        (name = "oauth", description = "OAuth2 authorization server"),
        (name = "security", description = "Security events & audit"),
        (name = "authz", description = "Authorization decisions"),
    ),
    paths(
        crate::domains::auth::routes::register::register,
        crate::domains::auth::routes::register::region,
        crate::domains::auth::routes::register::supported_regions,
        crate::domains::auth::routes::register::verify_email,
        crate::domains::auth::routes::login::identifier::challenge_identifier,
        crate::domains::auth::routes::login::mfa::challenge_mfa,
        crate::domains::auth::routes::login::pwd::challenge_pwd,
        crate::domains::auth::routes::login::webauthn::challenge_webauthn_start,
        crate::domains::auth::routes::login::webauthn::challenge_webauthn_discoverable_start,
        crate::domains::auth::routes::login::webauthn::challenge_webauthn_discoverable_finish,
        crate::domains::auth::routes::pow::challenge_pow,
        crate::domains::auth::routes::verification::change_verify_email,
        crate::domains::auth::routes::verification::resend_verify_email,
        crate::domains::auth::routes::session_mgmt::get_accounts,
        crate::domains::auth::routes::session_mgmt::list_sessions,
        crate::domains::auth::routes::session_mgmt::logout,
        crate::domains::auth::routes::session_mgmt::me,
        crate::domains::auth::routes::session_mgmt::profile::me_delete,
        crate::domains::auth::routes::session_mgmt::profile::me_preferences_get,
        crate::domains::auth::routes::session_mgmt::profile::me_preferences_put,
        crate::domains::auth::routes::session_mgmt::profile::me_notifications_get,
        crate::domains::auth::routes::session_mgmt::profile::me_notifications_put,
        crate::domains::auth::routes::session_mgmt::emails::me_emails_get,
        crate::domains::auth::routes::session_mgmt::emails::me_emails_post,
        crate::domains::auth::routes::session_mgmt::emails::me_email_promote,
        crate::domains::auth::routes::session_mgmt::emails::me_email_resend_verification,
        crate::domains::auth::routes::session_mgmt::emails::me_email_delete,
        crate::domains::auth::routes::session_mgmt::me_export,
        crate::domains::auth::routes::session_mgmt::me_export_download,
        crate::domains::auth::routes::session_mgmt::revoke_all_other_sessions,
        crate::domains::auth::routes::session_mgmt::revoke_session,
        crate::domains::auth::routes::session_mgmt::devices::trust_device,
        crate::domains::auth::routes::session_mgmt::devices::revoke_device,
        crate::domains::auth::routes::session_mgmt::step_up,
        crate::domains::auth::routes::mfa::list_mfa_factors,
        crate::domains::auth::routes::mfa::begin_totp_enrollment,
        crate::domains::auth::routes::mfa::confirm_totp_enrollment,
        crate::domains::auth::routes::mfa::webauthn_auth_start,
        crate::domains::auth::routes::mfa::begin_webauthn_enrollment,
        crate::domains::auth::routes::mfa::confirm_webauthn_enrollment,
        crate::domains::auth::routes::mfa::generate_recovery_codes,
        crate::domains::auth::routes::mfa::remove_mfa_factor,
        crate::domains::auth::routes::password::change_password,
        crate::domains::auth::routes::password::forgot_password,
        crate::domains::auth::routes::password::reset_password,
        crate::domains::auth::jwks::get_jwks,
        crate::domains::security::routes::list_security_events,
        crate::domains::security::routes::export_security_events,
        crate::domains::authz::routes::decide,
        crate::domains::legal::routes::grant_consent,
        crate::domains::legal::routes::gpc_status,
        crate::domains::legal::routes::list_consents,
        crate::domains::legal::routes::revoke_consent,
        crate::domains::oauth::routes::authorize::authorize,
        crate::domains::oauth::metadata::oauth_authorization_server_metadata,
        crate::domains::oauth::metadata::openid_configuration,
        crate::domains::oauth::routes::token::token,
        crate::domains::oauth::routes::userinfo::userinfo,
        crate::domains::oauth::routes::introspect::introspect,
        crate::domains::oauth::routes::revoke::revoke,
        crate::domains::oauth::routes::clients::list_clients,
        crate::domains::oauth::routes::clients::create_client,
        crate::domains::oauth::routes::clients::revoke_client,
        crate::domains::oauth::routes::clients::list_client_policies,
        crate::domains::oauth::routes::clients::create_client_policy,
        crate::domains::oauth::routes::clients::update_client_policy,
        crate::domains::oauth::routes::clients::delete_client_policy,
        crate::domains::oauth::routes::device::device_authorize,
        crate::domains::oauth::routes::device::device_verify,
        crate::domains::oauth::routes::device::device_approve,
        crate::domains::oauth::routes::device::device_deny,
        crate::http::well_known::change_password_well_known,
        crate::http::well_known::gpc_well_known,
        crate::http::well_known::passkey_endpoints_well_known,
        crate::http::well_known::webauthn_well_known,
    ),
)]
pub struct IdentityApiDoc;

pub fn openapi_routes() -> axum::Router<crate::app::AppState> {
    SwaggerUi::new("/docs")
        .url("/api/openapi.json", IdentityApiDoc::openapi())
        .into()
}
