use crate::app::AppState;
use axum::Router;

use super::{
    forget_account_cookie, get_accounts, list_sessions, logout, me, me_delete, me_email_delete,
    me_email_promote, me_email_resend_verification, me_emails_get, me_emails_post, me_export,
    me_export_download, me_notifications_get, me_notifications_put, me_preferences_get,
    me_preferences_put, me_update, revoke_all_other_sessions, revoke_session, step_up,
    switch_workspace,
};

pub(super) fn router(state: &AppState) -> Router<AppState> {
    Router::new()
        .route(
            "/logout",
            axum::routing::post(logout).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
        .route(
            "/sessions",
            axum::routing::get(list_sessions).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
        .route("/accounts", axum::routing::get(get_accounts))
        .route(
            "/accounts/{authuser}",
            axum::routing::delete(forget_account_cookie),
        )
        .route(
            "/sessions/{sessionId}",
            axum::routing::delete(revoke_session).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
        .route(
            "/sessions/revoke-others",
            axum::routing::post(revoke_all_other_sessions).layer(
                axum::middleware::from_fn_with_state(
                    state.clone(),
                    crate::http::middleware::jwt::jwt_auth_middleware,
                ),
            ),
        )
        .route(
            "/me",
            axum::routing::get(me).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
        .route(
            "/me",
            axum::routing::patch(me_update).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
        .route(
            "/me/emails",
            axum::routing::get(me_emails_get)
                .post(me_emails_post)
                .layer(axum::middleware::from_fn_with_state(
                    state.clone(),
                    crate::http::middleware::jwt::jwt_auth_middleware,
                )),
        )
        .route(
            "/me/emails/{emailId}/promote",
            axum::routing::post(me_email_promote).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
        .route(
            "/me/emails/{emailId}/resend-verification",
            axum::routing::post(me_email_resend_verification).layer(
                axum::middleware::from_fn_with_state(
                    state.clone(),
                    crate::http::middleware::jwt::jwt_auth_middleware,
                ),
            ),
        )
        .route(
            "/me/emails/{emailId}",
            axum::routing::delete(me_email_delete).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
        .route(
            "/me/export",
            axum::routing::post(me_export)
                .get(me_export_download)
                .layer(axum::middleware::from_fn_with_state(
                    state.clone(),
                    crate::http::middleware::jwt::jwt_auth_middleware,
                )),
        )
        .route(
            "/me/delete",
            axum::routing::post(me_delete).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
        .route(
            "/me/preferences",
            axum::routing::get(me_preferences_get).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
        .route(
            "/me/preferences",
            axum::routing::put(me_preferences_put).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
        .route(
            "/me/notifications",
            axum::routing::get(me_notifications_get).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
        .route(
            "/me/notifications",
            axum::routing::put(me_notifications_put).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
        .route(
            "/step-up",
            axum::routing::post(step_up).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
        .route(
            "/workspaces/{workspaceId}/switch",
            axum::routing::post(switch_workspace).layer(axum::middleware::from_fn_with_state(
                state.clone(),
                crate::http::middleware::jwt::jwt_auth_middleware,
            )),
        )
}
