import type { ReactNode } from 'react';
import { emailTheme, outlookExactLineHeight } from './email-ui.tokens';

export function EmailButton({ children, href }: { children: ReactNode; href: string }) {
  return (
    // A presentation table avoids the inline-block, min-width, and padding-on-link fallbacks
    // generated by React Email's Button, which are unreliable in Word-based Outlook clients.
    <table
      bgcolor={emailTheme.primary}
      border={0}
      cellPadding={0}
      cellSpacing={0}
      role="presentation"
    >
      <tbody>
        <tr>
          <td
            align="center"
            style={{
              backgroundColor: emailTheme.primary,
              borderRadius: emailTheme.radius,
              height: 48,
              width: 224,
            }}
          >
            <a
              href={href}
              style={{
                color: emailTheme.primaryForeground,
                fontSize: 15,
                fontWeight: 600,
                lineHeight: '22px',
                ...outlookExactLineHeight,
                textDecoration: 'none',
              }}
              target="_blank"
            >
              {children}
            </a>
          </td>
        </tr>
      </tbody>
    </table>
  );
}
