[package]
name = "nvbes-security-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
nvbes-dpop = { path = "../libs/rust/dpop" }

[[bin]]
name = "dpop-proof"
path = "fuzz_targets/dpop_proof.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
