use crate::openapi_paths::{CriticalEndpoint, e};

pub(crate) fn endpoints<'a>() -> Vec<CriticalEndpoint<'a>> {
    vec![
        e(
            "/workspaces/{workspaceId}/admin/revenue/dunning-cases/{caseId}/close",
            "closeDunningCase",
            "revenue",
            "Close a dunning case",
            &["workspaceId", "caseId"],
            "CriticalActionRequest",
            "RevenueActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/revenue/dunning-cases/{caseId}/reopen",
            "reopenDunningCase",
            "revenue",
            "Reopen a dunning case",
            &["workspaceId", "caseId"],
            "CriticalActionRequest",
            "RevenueActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/revenue/invoices/{invoiceId}/hold",
            "holdRevenueInvoice",
            "revenue",
            "Hold an invoice",
            &["workspaceId", "invoiceId"],
            "CriticalActionRequest",
            "RevenueActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/revenue/invoices/{invoiceId}/release",
            "releaseRevenueInvoice",
            "revenue",
            "Release an invoice hold",
            &["workspaceId", "invoiceId"],
            "CriticalActionRequest",
            "RevenueActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/revenue/disputes/{disputeId}/review",
            "reviewRevenueDispute",
            "revenue",
            "Mark a revenue dispute as under review",
            &["workspaceId", "disputeId"],
            "CriticalActionRequest",
            "RevenueActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/revenue/disputes/{disputeId}/resolve",
            "resolveRevenueDispute",
            "revenue",
            "Resolve a revenue dispute",
            &["workspaceId", "disputeId"],
            "CriticalActionRequest",
            "RevenueActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/billing-platform/routing-rules",
            "createBillingRoutingRule",
            "billing-platform",
            "Create a billing provider routing rule",
            &["workspaceId"],
            "CreateRoutingRuleRequest",
            "BillingPlatformActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/billing-platform/routing-rules/{ruleId}/enable",
            "enableBillingRoutingRule",
            "billing-platform",
            "Enable a billing provider routing rule",
            &["workspaceId", "ruleId"],
            "CriticalActionRequest",
            "BillingPlatformActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/billing-platform/routing-rules/{ruleId}/disable",
            "disableBillingRoutingRule",
            "billing-platform",
            "Disable a billing provider routing rule",
            &["workspaceId", "ruleId"],
            "CriticalActionRequest",
            "BillingPlatformActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/billing-platform/kyc-profiles/{profileId}/approve",
            "approveKycProfile",
            "billing-platform",
            "Approve a KYC profile",
            &["workspaceId", "profileId"],
            "CriticalActionRequest",
            "BillingPlatformActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/billing-platform/kyc-profiles/{profileId}/reject",
            "rejectKycProfile",
            "billing-platform",
            "Reject a KYC profile",
            &["workspaceId", "profileId"],
            "CriticalActionRequest",
            "BillingPlatformActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/billing-platform/einvoicing-profiles/{profileId}/activate",
            "activateEinvoicingProfile",
            "billing-platform",
            "Activate an e-invoicing profile",
            &["workspaceId", "profileId"],
            "CriticalActionRequest",
            "BillingPlatformActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/developer/clients/{clientId}/revoke",
            "revokeDeveloperClient",
            "developer",
            "Revoke a developer client",
            &["workspaceId", "clientId"],
            "CriticalActionRequest",
            "DeveloperActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/developer/clients/{clientId}/rotate-secret",
            "rotateDeveloperSecret",
            "developer",
            "Rotate a developer client secret",
            &["workspaceId", "clientId"],
            "CriticalActionRequest",
            "DeveloperActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/developer/marketplace-apps/{appId}/approve",
            "approveMarketplaceApp",
            "developer",
            "Approve a marketplace app",
            &["workspaceId", "appId"],
            "CriticalActionRequest",
            "DeveloperActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/entitlements/grants",
            "grantEntitlementFeature",
            "entitlements",
            "Grant an entitlement feature",
            &["workspaceId"],
            "EntitlementFeatureActionRequest",
            "EntitlementActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/entitlements/revocations",
            "revokeEntitlementFeature",
            "entitlements",
            "Revoke an entitlement feature",
            &["workspaceId"],
            "EntitlementFeatureActionRequest",
            "EntitlementActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/entitlements/quota-overrides",
            "overrideEntitlementQuota",
            "entitlements",
            "Override an entitlement quota",
            &["workspaceId"],
            "EntitlementQuotaOverrideRequest",
            "EntitlementActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/entitlements/publish",
            "publishEntitlementChanges",
            "entitlements",
            "Publish entitlement changes",
            &["workspaceId"],
            "CriticalActionRequest",
            "EntitlementActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/usage/corrections",
            "correctUsage",
            "usage",
            "Correct usage",
            &["workspaceId"],
            "UsageCorrectionRequest",
            "UsageActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/usage/meters/freeze",
            "freezeUsageMeter",
            "usage",
            "Freeze a usage meter",
            &["workspaceId"],
            "FreezeMeterRequest",
            "UsageActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/usage/rollups/{rollupId}/replay",
            "replayUsageRollup",
            "usage",
            "Replay a usage rollup",
            &["workspaceId", "rollupId"],
            "CriticalActionRequest",
            "UsageActionResult",
        ),
    ]
}
