use crate::openapi_paths::{CriticalEndpoint, e};

pub(crate) fn endpoints<'a>() -> Vec<CriticalEndpoint<'a>> {
    vec![
        e(
            "/workspaces/{workspaceId}/admin/operations/incidents/{incidentId}/state",
            "updateOperationsIncidentState",
            "operations",
            "Update an operations incident state",
            &["workspaceId", "incidentId"],
            "IncidentStateRequest",
            "OperationsActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/operations/maintenance-windows",
            "scheduleMaintenanceWindow",
            "operations",
            "Schedule an operations maintenance window",
            &["workspaceId"],
            "MaintenanceWindowRequest",
            "OperationsActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/operations/job-runs/{jobRunId}/replay",
            "replayOperationsJobRun",
            "operations",
            "Replay an operations job run",
            &["workspaceId", "jobRunId"],
            "CriticalActionRequest",
            "OperationsActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/communications/emails/{messageId}/replay",
            "replayEmailMessage",
            "communications",
            "Replay an email message",
            &["workspaceId", "messageId"],
            "CriticalActionRequest",
            "CommunicationsActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/communications/webhooks/{eventId}/replay",
            "replayWebhookEvent",
            "communications",
            "Replay a webhook event",
            &["workspaceId", "eventId"],
            "CriticalActionRequest",
            "CommunicationsActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/communications/suppressions",
            "suppressEmail",
            "communications",
            "Suppress an email address",
            &["workspaceId"],
            "SuppressionReviewRequest",
            "CommunicationsActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/communications/suppressions/remove",
            "unsuppressEmail",
            "communications",
            "Unsuppress an email address",
            &["workspaceId"],
            "SuppressionReviewRequest",
            "CommunicationsActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/compliance/consents/{consentId}/revoke",
            "revokeConsent",
            "compliance",
            "Revoke a consent",
            &["workspaceId", "consentId"],
            "CriticalActionRequest",
            "ComplianceActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/compliance/principals/{principalId}/erasure-request",
            "requestComplianceErasure",
            "compliance",
            "Request principal erasure",
            &["workspaceId", "principalId"],
            "CriticalActionRequest",
            "ComplianceActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/compliance/suppressions/review",
            "reviewComplianceSuppression",
            "compliance",
            "Review email suppression",
            &["workspaceId"],
            "SuppressionReviewRequest",
            "ComplianceActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/region/workspaces/{targetWorkspaceId}/residency-flag",
            "flagWorkspaceResidency",
            "region",
            "Flag workspace data residency",
            &["workspaceId", "targetWorkspaceId"],
            "RegionFlagRequest",
            "RegionActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/region/workspaces/{targetWorkspaceId}/exceptions",
            "recordRegionException",
            "region",
            "Record a data residency exception",
            &["workspaceId", "targetWorkspaceId"],
            "RegionExceptionRequest",
            "RegionActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/risk/policies/{policyId}/approve",
            "approveRiskPolicy",
            "risk",
            "Approve a risk policy",
            &["workspaceId", "policyId"],
            "CriticalActionRequest",
            "RiskActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/risk/policies/{policyId}/block",
            "blockRiskPolicy",
            "risk",
            "Block a risk policy",
            &["workspaceId", "policyId"],
            "CriticalActionRequest",
            "RiskActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/risk/signals/{signalId}/resolve",
            "resolveRiskSignal",
            "risk",
            "Resolve a risk signal",
            &["workspaceId", "signalId"],
            "CriticalActionRequest",
            "RiskActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/operations/provider-events/{eventId}/replay",
            "replayOperationsProviderEvent",
            "operations",
            "Replay an operations provider event",
            &["workspaceId", "eventId"],
            "CriticalActionRequest",
            "OperationsActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/operations/export-runs/{exportRunId}/replay",
            "replayExportRun",
            "operations",
            "Replay an export run",
            &["workspaceId", "exportRunId"],
            "CriticalActionRequest",
            "OperationsActionResult",
        ),
        e(
            "/workspaces/{workspaceId}/admin/operations/reconciliation-differences/{differenceId}/resolve",
            "resolveReconciliationDifference",
            "operations",
            "Resolve a reconciliation difference",
            &["workspaceId", "differenceId"],
            "CriticalActionRequest",
            "OperationsActionResult",
        ),
    ]
}
