packages:
  - apps/*
  - libs/ts/*

catalog:
  react: ^19.2.6
  react-dom: ^19.2.6
  '@tanstack/react-query': ^5.90.12
  '@tanstack/react-query-devtools': ^5.91.0
  '@tanstack/react-router': ^1.139.10
  '@tanstack/react-router-devtools': ^1.139.10
  typescript: ^6.0.3
  '@typescript/native-preview': npm:@typescript/native-preview@beta
  vite: npm:@voidzero-dev/vite-plus-core@0.1.24
  vite-plus: ^0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24
  '@vitejs/plugin-react': ^6.0.2
  react-router-dom: ^7.15.1
  tsx: ^4.22.1
  '@tailwindcss/vite': ^4.3.0
  tailwindcss: ^4.3.0
  tsup: ^8.3.6

allowBuilds:
  core-js: true
  esbuild: true
  msw: true
  nx: true
  protobufjs: true

overrides:
  yaml: '>=2.8.3'

minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-core@0.1.24'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.1.24'
  - '@voidzero-dev/vite-plus-darwin-x64@0.1.24'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.1.24'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.1.24'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.1.24'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.1.24'
  - '@voidzero-dev/vite-plus-test@0.1.24'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.1.24'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.1.24'
  - vite-plus@0.1.24
