use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const ASIA_PACIFIC_PROFILES: &[RegionProfile] = &[
    RegionProfile {
        country_code: "AF",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_KABUL,
        timezones: &[TZ_ASIA_KABUL],
        sub_region: None,
        display_name: Some("Afghanistan"),
    },
    RegionProfile {
        country_code: "AU",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::App,
        primary_timezone: TZ_AUSTRALIA_SYDNEY,
        timezones: &[
            TZ_AUSTRALIA_SYDNEY,
            TZ_AUSTRALIA_MELBOURNE,
            TZ_AUSTRALIA_BRISBANE,
            TZ_AUSTRALIA_ADELAIDE,
            TZ_AUSTRALIA_DARWIN,
            TZ_AUSTRALIA_PERTH,
            TZ_AUSTRALIA_HOBART,
            TZ_AUSTRALIA_LORD_HOWE,
            TZ_AUSTRALIA_BROKEN_HILL,
            TZ_AUSTRALIA_EUCLA,
        ],
        sub_region: None,
        display_name: Some("Australia"),
    },
    RegionProfile {
        country_code: "BD",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_DHAKA,
        timezones: &[TZ_ASIA_DHAKA],
        sub_region: None,
        display_name: Some("Bangladesh"),
    },
    RegionProfile {
        country_code: "BT",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_THIMPHU,
        timezones: &[TZ_ASIA_THIMPHU],
        sub_region: None,
        display_name: Some("Bhutan"),
    },
    RegionProfile {
        country_code: "BN",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_BANDAR_SERI_BEGAWAN,
        timezones: &[TZ_ASIA_BANDAR_SERI_BEGAWAN],
        sub_region: None,
        display_name: Some("Brunei"),
    },
    RegionProfile {
        country_code: "KH",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_PHNOM_PENH,
        timezones: &[TZ_ASIA_PHNOM_PENH],
        sub_region: None,
        display_name: Some("Cambodia"),
    },
    RegionProfile {
        country_code: "CN",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Pipl,
        primary_timezone: TZ_ASIA_SHANGHAI,
        timezones: &[TZ_ASIA_SHANGHAI],
        sub_region: None,
        display_name: Some("China"),
    },
    RegionProfile {
        country_code: "FJ",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_FIJI,
        timezones: &[TZ_PACIFIC_FIJI],
        sub_region: None,
        display_name: Some("Fiji"),
    },
    RegionProfile {
        country_code: "IN",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_KOLKATA,
        timezones: &[TZ_ASIA_KOLKATA],
        sub_region: None,
        display_name: Some("India"),
    },
    RegionProfile {
        country_code: "ID",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_JAKARTA,
        timezones: &[
            TZ_ASIA_JAKARTA,
            TZ_ASIA_PONTIANAK,
            TZ_ASIA_MAKASSAR,
            TZ_ASIA_JAYAPURA,
        ],
        sub_region: None,
        display_name: Some("Indonesia"),
    },
    RegionProfile {
        country_code: "JP",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_TOKYO,
        timezones: &[TZ_ASIA_TOKYO],
        sub_region: None,
        display_name: Some("Japan"),
    },
    RegionProfile {
        country_code: "KZ",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_ALMATY,
        timezones: &[
            TZ_ASIA_ALMATY,
            TZ_ASIA_AQTOBE,
            TZ_ASIA_ATYRAU,
            TZ_ASIA_QOSTANAY,
            TZ_ASIA_QYZYLORDA,
            TZ_ASIA_ORAL,
        ],
        sub_region: None,
        display_name: Some("Kazakhstan"),
    },
    RegionProfile {
        country_code: "KI",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_TARAWA,
        timezones: &[TZ_PACIFIC_TARAWA, TZ_PACIFIC_KANTON, TZ_PACIFIC_KIRITIMATI],
        sub_region: None,
        display_name: Some("Kiribati"),
    },
    RegionProfile {
        country_code: "KP",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_PYONGYANG,
        timezones: &[TZ_ASIA_PYONGYANG],
        sub_region: None,
        display_name: Some("North Korea"),
    },
    RegionProfile {
        country_code: "KR",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_SEOUL,
        timezones: &[TZ_ASIA_SEOUL],
        sub_region: None,
        display_name: Some("South Korea"),
    },
    RegionProfile {
        country_code: "KG",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_BISHKEK,
        timezones: &[TZ_ASIA_BISHKEK],
        sub_region: None,
        display_name: Some("Kyrgyzstan"),
    },
    RegionProfile {
        country_code: "LA",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_VIENTIANE,
        timezones: &[TZ_ASIA_VIENTIANE],
        sub_region: None,
        display_name: Some("Laos"),
    },
    RegionProfile {
        country_code: "MY",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Pdpa,
        primary_timezone: TZ_ASIA_KUALA_LUMPUR,
        timezones: &[TZ_ASIA_KUALA_LUMPUR],
        sub_region: None,
        display_name: Some("Malaysia"),
    },
    RegionProfile {
        country_code: "MV",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_INDIAN_MALDIVES,
        timezones: &[TZ_INDIAN_MALDIVES],
        sub_region: None,
        display_name: Some("Maldives"),
    },
    RegionProfile {
        country_code: "MH",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_MAJURO,
        timezones: &[TZ_PACIFIC_MAJURO, TZ_PACIFIC_KWAJALEIN],
        sub_region: None,
        display_name: Some("Marshall Islands"),
    },
    RegionProfile {
        country_code: "FM",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_POHNPEI,
        timezones: &[TZ_PACIFIC_POHNPEI, TZ_PACIFIC_KOSRAE, TZ_PACIFIC_CHUUK],
        sub_region: None,
        display_name: Some("Micronesia"),
    },
    RegionProfile {
        country_code: "MN",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_ULAANBAATAR,
        timezones: &[TZ_ASIA_ULAANBAATAR, TZ_ASIA_HOVD, TZ_ASIA_CHOIBALSAN],
        sub_region: None,
        display_name: Some("Mongolia"),
    },
    RegionProfile {
        country_code: "MM",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_YANGON,
        timezones: &[TZ_ASIA_YANGON],
        sub_region: None,
        display_name: Some("Myanmar"),
    },
    RegionProfile {
        country_code: "NR",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_NAURU,
        timezones: &[TZ_PACIFIC_NAURU],
        sub_region: None,
        display_name: Some("Nauru"),
    },
    RegionProfile {
        country_code: "NP",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_KATHMANDU,
        timezones: &[TZ_ASIA_KATHMANDU],
        sub_region: None,
        display_name: Some("Nepal"),
    },
    RegionProfile {
        country_code: "NZ",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::App,
        primary_timezone: TZ_PACIFIC_AUCKLAND,
        timezones: &[TZ_PACIFIC_AUCKLAND, TZ_PACIFIC_CHATHAM],
        sub_region: None,
        display_name: Some("New Zealand"),
    },
    RegionProfile {
        country_code: "PK",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_KARACHI,
        timezones: &[TZ_ASIA_KARACHI],
        sub_region: None,
        display_name: Some("Pakistan"),
    },
    RegionProfile {
        country_code: "PW",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_PALAU,
        timezones: &[TZ_PACIFIC_PALAU],
        sub_region: None,
        display_name: Some("Palau"),
    },
    RegionProfile {
        country_code: "PG",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_PORT_MORESBY,
        timezones: &[TZ_PACIFIC_PORT_MORESBY, TZ_PACIFIC_BOUGAINVILLE],
        sub_region: None,
        display_name: Some("Papua New Guinea"),
    },
    RegionProfile {
        country_code: "PH",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_MANILA,
        timezones: &[TZ_ASIA_MANILA],
        sub_region: None,
        display_name: Some("Philippines"),
    },
    RegionProfile {
        country_code: "WS",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_APIA,
        timezones: &[TZ_PACIFIC_APIA],
        sub_region: None,
        display_name: Some("Samoa"),
    },
    RegionProfile {
        country_code: "SG",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Pdpa,
        primary_timezone: TZ_ASIA_SINGAPORE,
        timezones: &[TZ_ASIA_SINGAPORE],
        sub_region: None,
        display_name: Some("Singapore"),
    },
    RegionProfile {
        country_code: "SB",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_GUADALCANAL,
        timezones: &[TZ_PACIFIC_GUADALCANAL],
        sub_region: None,
        display_name: Some("Solomon Islands"),
    },
    RegionProfile {
        country_code: "LK",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_COLOMBO,
        timezones: &[TZ_ASIA_COLOMBO],
        sub_region: None,
        display_name: Some("Sri Lanka"),
    },
    RegionProfile {
        country_code: "TW",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_TAIPEI,
        timezones: &[TZ_ASIA_TAIPEI],
        sub_region: None,
        display_name: Some("Taiwan"),
    },
    RegionProfile {
        country_code: "TJ",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_DUSHANBE,
        timezones: &[TZ_ASIA_DUSHANBE],
        sub_region: None,
        display_name: Some("Tajikistan"),
    },
    RegionProfile {
        country_code: "TH",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Pdpa,
        primary_timezone: TZ_ASIA_BANGKOK,
        timezones: &[TZ_ASIA_BANGKOK],
        sub_region: None,
        display_name: Some("Thailand"),
    },
    RegionProfile {
        country_code: "TL",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_DILI,
        timezones: &[TZ_ASIA_DILI],
        sub_region: None,
        display_name: Some("Timor-Leste"),
    },
    RegionProfile {
        country_code: "TO",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_TONGATAPU,
        timezones: &[TZ_PACIFIC_TONGATAPU],
        sub_region: None,
        display_name: Some("Tonga"),
    },
    RegionProfile {
        country_code: "TM",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_ASHGABAT,
        timezones: &[TZ_ASIA_ASHGABAT],
        sub_region: None,
        display_name: Some("Turkmenistan"),
    },
    RegionProfile {
        country_code: "TV",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_FUNAFUTI,
        timezones: &[TZ_PACIFIC_FUNAFUTI],
        sub_region: None,
        display_name: Some("Tuvalu"),
    },
    RegionProfile {
        country_code: "UZ",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_TASHKENT,
        timezones: &[TZ_ASIA_TASHKENT],
        sub_region: None,
        display_name: Some("Uzbekistan"),
    },
    RegionProfile {
        country_code: "VU",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_EFATE,
        timezones: &[TZ_PACIFIC_EFATE],
        sub_region: None,
        display_name: Some("Vanuatu"),
    },
    RegionProfile {
        country_code: "VN",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_HANOI,
        timezones: &[TZ_ASIA_HANOI],
        sub_region: None,
        display_name: Some("Vietnam"),
    },
    RegionProfile {
        country_code: "CK",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_RAROTONGA,
        timezones: &[TZ_PACIFIC_RAROTONGA],
        sub_region: Some("New Zealand"),
        display_name: Some("Cook Islands"),
    },
    RegionProfile {
        country_code: "NU",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_NIUE,
        timezones: &[TZ_PACIFIC_NIUE],
        sub_region: Some("New Zealand"),
        display_name: Some("Niue"),
    },
    RegionProfile {
        country_code: "TK",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_FAKAOFO,
        timezones: &[TZ_PACIFIC_FAKAOFO],
        sub_region: Some("New Zealand"),
        display_name: Some("Tokelau"),
    },
    RegionProfile {
        country_code: "HK",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_HONG_KONG,
        timezones: &[TZ_ASIA_HONG_KONG],
        sub_region: Some("China"),
        display_name: Some("Hong Kong"),
    },
    RegionProfile {
        country_code: "MO",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_MACAU,
        timezones: &[TZ_ASIA_MACAU],
        sub_region: Some("China"),
        display_name: Some("Macau"),
    },
    RegionProfile {
        country_code: "NF",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::App,
        primary_timezone: TZ_PACIFIC_NORFOLK,
        timezones: &[TZ_PACIFIC_NORFOLK],
        sub_region: Some("Australia"),
        display_name: Some("Norfolk Island"),
    },
    RegionProfile {
        country_code: "CX",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::App,
        primary_timezone: TZ_ASIA_JAKARTA,
        timezones: &[TZ_ASIA_JAKARTA],
        sub_region: Some("Australia"),
        display_name: Some("Christmas Island"),
    },
    RegionProfile {
        country_code: "CC",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::App,
        primary_timezone: TZ_ASIA_JAKARTA,
        timezones: &[TZ_ASIA_JAKARTA],
        sub_region: Some("Australia"),
        display_name: Some("Cocos (Keeling) Islands"),
    },
    RegionProfile {
        country_code: "PN",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_PACIFIC_PITCAIRN,
        timezones: &[TZ_PACIFIC_PITCAIRN],
        sub_region: Some("United Kingdom"),
        display_name: Some("Pitcairn Islands"),
    },
];
