use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const AFRICA_ME_PROFILES_PART_2: &[RegionProfile] = &[
    RegionProfile {
        country_code: "KE",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Kdpa,
        primary_timezone: TZ_AFRICA_NAIROBI,
        timezones: &[TZ_AFRICA_NAIROBI],
        sub_region: None,
        display_name: Some("Kenya"),
    },
    RegionProfile {
        country_code: "LS",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MASERU,
        timezones: &[TZ_AFRICA_MASERU],
        sub_region: None,
        display_name: Some("Lesotho"),
    },
    RegionProfile {
        country_code: "LR",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MONROVIA,
        timezones: &[TZ_AFRICA_MONROVIA],
        sub_region: None,
        display_name: Some("Liberia"),
    },
    RegionProfile {
        country_code: "LY",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_TRIPOLI,
        timezones: &[TZ_AFRICA_TRIPOLI],
        sub_region: None,
        display_name: Some("Libya"),
    },
    RegionProfile {
        country_code: "MG",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_ANTANANARIVO,
        timezones: &[TZ_AFRICA_ANTANANARIVO],
        sub_region: None,
        display_name: Some("Madagascar"),
    },
    RegionProfile {
        country_code: "MW",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_LILONGWE,
        timezones: &[TZ_AFRICA_LILONGWE],
        sub_region: None,
        display_name: Some("Malawi"),
    },
    RegionProfile {
        country_code: "ML",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_BAMAKO,
        timezones: &[TZ_AFRICA_BAMAKO],
        sub_region: None,
        display_name: Some("Mali"),
    },
    RegionProfile {
        country_code: "MR",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_NOUAKCHOTT,
        timezones: &[TZ_AFRICA_NOUAKCHOTT],
        sub_region: None,
        display_name: Some("Mauritania"),
    },
    RegionProfile {
        country_code: "MU",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MAURITIUS,
        timezones: &[TZ_AFRICA_MAURITIUS],
        sub_region: None,
        display_name: Some("Mauritius"),
    },
    RegionProfile {
        country_code: "MA",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Cndp,
        primary_timezone: TZ_AFRICA_CASABLANCA,
        timezones: &[TZ_AFRICA_CASABLANCA],
        sub_region: None,
        display_name: Some("Morocco"),
    },
    RegionProfile {
        country_code: "MZ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MAPUTO,
        timezones: &[TZ_AFRICA_MAPUTO],
        sub_region: None,
        display_name: Some("Mozambique"),
    },
    RegionProfile {
        country_code: "NA",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_WINDHOEK,
        timezones: &[TZ_AFRICA_WINDHOEK],
        sub_region: None,
        display_name: Some("Namibia"),
    },
    RegionProfile {
        country_code: "NE",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_NIAMEY,
        timezones: &[TZ_AFRICA_NIAMEY],
        sub_region: None,
        display_name: Some("Niger"),
    },
    RegionProfile {
        country_code: "NG",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Ndpa,
        primary_timezone: TZ_AFRICA_LAGOS,
        timezones: &[TZ_AFRICA_LAGOS],
        sub_region: None,
        display_name: Some("Nigeria"),
    },
    RegionProfile {
        country_code: "RW",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_KIGALI,
        timezones: &[TZ_AFRICA_KIGALI],
        sub_region: None,
        display_name: Some("Rwanda"),
    },
    RegionProfile {
        country_code: "ST",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_SAO_TOME,
        timezones: &[TZ_AFRICA_SAO_TOME],
        sub_region: None,
        display_name: Some("Sao Tome and Principe"),
    },
    RegionProfile {
        country_code: "SN",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_DAKAR,
        timezones: &[TZ_AFRICA_DAKAR],
        sub_region: None,
        display_name: Some("Senegal"),
    },
    RegionProfile {
        country_code: "SC",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_SEYCHELLES,
        timezones: &[TZ_AFRICA_SEYCHELLES],
        sub_region: None,
        display_name: Some("Seychelles"),
    },
    RegionProfile {
        country_code: "SL",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_FREETOWN,
        timezones: &[TZ_AFRICA_FREETOWN],
        sub_region: None,
        display_name: Some("Sierra Leone"),
    },
    RegionProfile {
        country_code: "SO",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MOGADISHU,
        timezones: &[TZ_AFRICA_MOGADISHU],
        sub_region: None,
        display_name: Some("Somalia"),
    },
    RegionProfile {
        country_code: "ZA",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Popia,
        primary_timezone: TZ_AFRICA_JOHANNESBURG,
        timezones: &[TZ_AFRICA_JOHANNESBURG],
        sub_region: None,
        display_name: Some("South Africa"),
    },
    RegionProfile {
        country_code: "SS",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_JUBA,
        timezones: &[TZ_AFRICA_JUBA],
        sub_region: None,
        display_name: Some("South Sudan"),
    },
    RegionProfile {
        country_code: "SD",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_KHARTOUM,
        timezones: &[TZ_AFRICA_KHARTOUM],
        sub_region: None,
        display_name: Some("Sudan"),
    },
    RegionProfile {
        country_code: "TZ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_DAR_ES_SALAAM,
        timezones: &[TZ_AFRICA_DAR_ES_SALAAM],
        sub_region: None,
        display_name: Some("Tanzania"),
    },
    RegionProfile {
        country_code: "TG",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_LOME,
        timezones: &[TZ_AFRICA_LOME],
        sub_region: None,
        display_name: Some("Togo"),
    },
];
