use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const AFRICA_ME_PROFILES_PART_1: &[RegionProfile] = &[
    RegionProfile {
        country_code: "DZ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Apdp,
        primary_timezone: TZ_AFRICA_ALGIERS,
        timezones: &[TZ_AFRICA_ALGIERS],
        sub_region: None,
        display_name: Some("Algeria"),
    },
    RegionProfile {
        country_code: "AO",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_LUANDA,
        timezones: &[TZ_AFRICA_LUANDA],
        sub_region: None,
        display_name: Some("Angola"),
    },
    RegionProfile {
        country_code: "BJ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_PORTO_NOVO,
        timezones: &[TZ_AFRICA_PORTO_NOVO],
        sub_region: None,
        display_name: Some("Benin"),
    },
    RegionProfile {
        country_code: "BW",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_GABORONE,
        timezones: &[TZ_AFRICA_GABORONE],
        sub_region: None,
        display_name: Some("Botswana"),
    },
    RegionProfile {
        country_code: "BF",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_OUAGADOUGOU,
        timezones: &[TZ_AFRICA_OUAGADOUGOU],
        sub_region: None,
        display_name: Some("Burkina Faso"),
    },
    RegionProfile {
        country_code: "BI",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_BUJUMBURA,
        timezones: &[TZ_AFRICA_BUJUMBURA],
        sub_region: None,
        display_name: Some("Burundi"),
    },
    RegionProfile {
        country_code: "CV",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ATLANTIC_CAPE_VERDE,
        timezones: &[TZ_ATLANTIC_CAPE_VERDE],
        sub_region: None,
        display_name: Some("Cabo Verde"),
    },
    RegionProfile {
        country_code: "CM",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_YAOUNDE,
        timezones: &[TZ_AFRICA_YAOUNDE],
        sub_region: None,
        display_name: Some("Cameroon"),
    },
    RegionProfile {
        country_code: "CF",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_BANGUI,
        timezones: &[TZ_AFRICA_BANGUI],
        sub_region: None,
        display_name: Some("Central African Republic"),
    },
    RegionProfile {
        country_code: "TD",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_NDJAMENA,
        timezones: &[TZ_AFRICA_NDJAMENA],
        sub_region: None,
        display_name: Some("Chad"),
    },
    RegionProfile {
        country_code: "KM",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_COMORO,
        timezones: &[TZ_AFRICA_COMORO],
        sub_region: None,
        display_name: Some("Comoros"),
    },
    RegionProfile {
        country_code: "CG",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_BRAZZAVILLE,
        timezones: &[TZ_AFRICA_BRAZZAVILLE],
        sub_region: None,
        display_name: Some("Congo"),
    },
    RegionProfile {
        country_code: "CD",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_KINSHASA,
        timezones: &[TZ_AFRICA_KINSHASA, TZ_AFRICA_LUBUMBASHI],
        sub_region: None,
        display_name: Some("Democratic Republic of the Congo"),
    },
    RegionProfile {
        country_code: "CI",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_ABIDJAN,
        timezones: &[TZ_AFRICA_ABIDJAN],
        sub_region: None,
        display_name: Some("Cote d'Ivoire"),
    },
    RegionProfile {
        country_code: "DJ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_ADDIS_ABABA,
        timezones: &[TZ_AFRICA_ADDIS_ABABA],
        sub_region: None,
        display_name: Some("Djibouti"),
    },
    RegionProfile {
        country_code: "EG",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Edpl,
        primary_timezone: TZ_AFRICA_CAIRO,
        timezones: &[TZ_AFRICA_CAIRO],
        sub_region: None,
        display_name: Some("Egypt"),
    },
    RegionProfile {
        country_code: "GQ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MALABO,
        timezones: &[TZ_AFRICA_MALABO],
        sub_region: None,
        display_name: Some("Equatorial Guinea"),
    },
    RegionProfile {
        country_code: "ER",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_ASMARA,
        timezones: &[TZ_AFRICA_ASMARA],
        sub_region: None,
        display_name: Some("Eritrea"),
    },
    RegionProfile {
        country_code: "SZ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MBABANE,
        timezones: &[TZ_AFRICA_MBABANE],
        sub_region: None,
        display_name: Some("Eswatini"),
    },
    RegionProfile {
        country_code: "ET",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_ADDIS_ABABA,
        timezones: &[TZ_AFRICA_ADDIS_ABABA],
        sub_region: None,
        display_name: Some("Ethiopia"),
    },
    RegionProfile {
        country_code: "GA",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_LIBREVILLE,
        timezones: &[TZ_AFRICA_LIBREVILLE],
        sub_region: None,
        display_name: Some("Gabon"),
    },
    RegionProfile {
        country_code: "GM",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_BANJUL,
        timezones: &[TZ_AFRICA_BANJUL],
        sub_region: None,
        display_name: Some("Gambia"),
    },
    RegionProfile {
        country_code: "GH",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_ACCRA,
        timezones: &[TZ_AFRICA_ACCRA],
        sub_region: None,
        display_name: Some("Ghana"),
    },
    RegionProfile {
        country_code: "GN",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_CONAKRY,
        timezones: &[TZ_AFRICA_CONAKRY],
        sub_region: None,
        display_name: Some("Guinea"),
    },
    RegionProfile {
        country_code: "GW",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_BISSAU,
        timezones: &[TZ_AFRICA_BISSAU],
        sub_region: None,
        display_name: Some("Guinea-Bissau"),
    },
];
