#[path = "region.timezones.africa.rs"]
mod africa;
#[path = "region.timezones.america.rs"]
mod america;
#[path = "region.timezones.asia.rs"]
mod asia;
#[path = "region.timezones.europe.rs"]
mod europe;
#[path = "region.timezones.oceania.rs"]
mod oceania;
#[path = "region.timezones.other.rs"]
mod other;

pub use africa::{
    TZ_AFRICA_ABIDJAN, TZ_AFRICA_ACCRA, TZ_AFRICA_ADDIS_ABABA, TZ_AFRICA_ALGIERS,
    TZ_AFRICA_ANTANANARIVO, TZ_AFRICA_ASMARA, TZ_AFRICA_BAMAKO, TZ_AFRICA_BANGUI, TZ_AFRICA_BANJUL,
    TZ_AFRICA_BISSAU, TZ_AFRICA_BRAZZAVILLE, TZ_AFRICA_BUJUMBURA, TZ_AFRICA_CAIRO,
    TZ_AFRICA_CASABLANCA, TZ_AFRICA_CEUTA, TZ_AFRICA_COMORO, TZ_AFRICA_CONAKRY, TZ_AFRICA_DAKAR,
    TZ_AFRICA_DAR_ES_SALAAM, TZ_AFRICA_EL_AAIUN, TZ_AFRICA_FREETOWN, TZ_AFRICA_GABORONE,
    TZ_AFRICA_HARARE, TZ_AFRICA_JOHANNESBURG, TZ_AFRICA_JUBA, TZ_AFRICA_KAMPALA,
    TZ_AFRICA_KHARTOUM, TZ_AFRICA_KIGALI, TZ_AFRICA_KINSHASA, TZ_AFRICA_LAGOS,
    TZ_AFRICA_LIBREVILLE, TZ_AFRICA_LILONGWE, TZ_AFRICA_LOME, TZ_AFRICA_LUANDA,
    TZ_AFRICA_LUBUMBASHI, TZ_AFRICA_LUSAKA, TZ_AFRICA_MALABO, TZ_AFRICA_MAPUTO, TZ_AFRICA_MASERU,
    TZ_AFRICA_MAURITIUS, TZ_AFRICA_MAYOTTE, TZ_AFRICA_MBABANE, TZ_AFRICA_MOGADISHU,
    TZ_AFRICA_MONROVIA, TZ_AFRICA_NAIROBI, TZ_AFRICA_NDJAMENA, TZ_AFRICA_NIAMEY,
    TZ_AFRICA_NOUAKCHOTT, TZ_AFRICA_OUAGADOUGOU, TZ_AFRICA_PORTO_NOVO, TZ_AFRICA_REUNION,
    TZ_AFRICA_SAO_TOME, TZ_AFRICA_SEYCHELLES, TZ_AFRICA_TRIPOLI, TZ_AFRICA_TUNIS,
    TZ_AFRICA_WINDHOEK, TZ_AFRICA_YAOUNDE,
};
pub use america::{
    TZ_AMERICA_ADAK, TZ_AMERICA_ANCHORAGE, TZ_AMERICA_ANGUILLA, TZ_AMERICA_ANTIGUA,
    TZ_AMERICA_ARAGUAINA, TZ_AMERICA_ARGENTINA_BUENOS_AIRES, TZ_AMERICA_ARGENTINA_MENDOZA,
    TZ_AMERICA_ARGENTINA_RIO_GALLEGOS, TZ_AMERICA_ARGENTINA_USHUAIA, TZ_AMERICA_ARUBA,
    TZ_AMERICA_ASUNCION, TZ_AMERICA_BAHIA, TZ_AMERICA_BARBADOS, TZ_AMERICA_BELEM,
    TZ_AMERICA_BELIZE, TZ_AMERICA_BLANC_SABLON, TZ_AMERICA_BOA_VISTA, TZ_AMERICA_BOGOTA,
    TZ_AMERICA_BOISE, TZ_AMERICA_CAMBRIDGE_BAY, TZ_AMERICA_CAMPO_GRANDE, TZ_AMERICA_CANCUN,
    TZ_AMERICA_CARACAS, TZ_AMERICA_CAYENNE, TZ_AMERICA_CHICAGO, TZ_AMERICA_CHIHUAHUA,
    TZ_AMERICA_CIUDAD_JUAREZ, TZ_AMERICA_COSTA_RICA, TZ_AMERICA_CRESTON, TZ_AMERICA_CUIABA,
    TZ_AMERICA_CURACAO, TZ_AMERICA_DANMARKSHAVN, TZ_AMERICA_DAWSON, TZ_AMERICA_DENVER,
    TZ_AMERICA_DOMINICA, TZ_AMERICA_EASTER, TZ_AMERICA_EDMONTON, TZ_AMERICA_EIRUNEPE,
    TZ_AMERICA_EL_SALVADOR, TZ_AMERICA_FORT_NELSON, TZ_AMERICA_FORTALEZA, TZ_AMERICA_GODTHAB,
    TZ_AMERICA_GOOSE_BAY, TZ_AMERICA_GRAND_TURK, TZ_AMERICA_GRENADA, TZ_AMERICA_GUADELOUPE,
    TZ_AMERICA_GUATEMALA, TZ_AMERICA_GUAYAQUIL, TZ_AMERICA_GUYANA, TZ_AMERICA_HALIFAX,
    TZ_AMERICA_HAMILTON, TZ_AMERICA_HAVANA, TZ_AMERICA_HERMOSILLO, TZ_AMERICA_HONOLULU,
    TZ_AMERICA_INDIANA_INDIANAPOLIS, TZ_AMERICA_INUVIK, TZ_AMERICA_IQALUIT, TZ_AMERICA_JAMAICA,
    TZ_AMERICA_JUNEAU, TZ_AMERICA_KRALENDIJK, TZ_AMERICA_LA_PAZ, TZ_AMERICA_LIMA,
    TZ_AMERICA_LOS_ANGELES, TZ_AMERICA_MACEIO, TZ_AMERICA_MANAGUA, TZ_AMERICA_MANAUS,
    TZ_AMERICA_MARIGOT, TZ_AMERICA_MARTINIQUE, TZ_AMERICA_MAZATLAN, TZ_AMERICA_MERIDA,
    TZ_AMERICA_METLAKATLA, TZ_AMERICA_MEXICO_CITY, TZ_AMERICA_MIQUELON, TZ_AMERICA_MONTERREY,
    TZ_AMERICA_MONTEVIDEO, TZ_AMERICA_MONTSERRAT, TZ_AMERICA_NASSAU, TZ_AMERICA_NEW_YORK,
    TZ_AMERICA_NOME, TZ_AMERICA_NORONHA, TZ_AMERICA_NUUK, TZ_AMERICA_PANAMA, TZ_AMERICA_PARAMARIBO,
    TZ_AMERICA_PHOENIX, TZ_AMERICA_PORT_AU_PRINCE, TZ_AMERICA_PORT_OF_SPAIN,
    TZ_AMERICA_PORTO_VELHO, TZ_AMERICA_PUERTO_RICO, TZ_AMERICA_PUNTA_ARENAS,
    TZ_AMERICA_RANKIN_INLET, TZ_AMERICA_RECIFE, TZ_AMERICA_REGINA, TZ_AMERICA_RESOLUTE,
    TZ_AMERICA_RIO_BRANCO, TZ_AMERICA_SANTAREM, TZ_AMERICA_SANTIAGO, TZ_AMERICA_SANTO_DOMINGO,
    TZ_AMERICA_SAO_PAULO, TZ_AMERICA_SCORESBYSUND, TZ_AMERICA_SITKA, TZ_AMERICA_ST_BARTHELEMY,
    TZ_AMERICA_ST_JOHNS, TZ_AMERICA_ST_KITTS, TZ_AMERICA_ST_LUCIA, TZ_AMERICA_ST_THOMAS,
    TZ_AMERICA_ST_VINCENT, TZ_AMERICA_TEGUCIGALPA, TZ_AMERICA_THULE, TZ_AMERICA_TIJUANA,
    TZ_AMERICA_TORONTO, TZ_AMERICA_TORTOLA, TZ_AMERICA_VANCOUVER, TZ_AMERICA_WHITEHORSE,
    TZ_AMERICA_WINNIPEG, TZ_AMERICA_YAKUTAT, TZ_AMERICA_YELLOWKNIFE,
};
pub use asia::{
    TZ_ASIA_ADEN, TZ_ASIA_ALMATY, TZ_ASIA_AMMAN, TZ_ASIA_ANADYR, TZ_ASIA_AQTOBE, TZ_ASIA_ASHGABAT,
    TZ_ASIA_ATYRAU, TZ_ASIA_BAGHDAD, TZ_ASIA_BAKU, TZ_ASIA_BANDAR_SERI_BEGAWAN, TZ_ASIA_BANGKOK,
    TZ_ASIA_BEIRUT, TZ_ASIA_BISHKEK, TZ_ASIA_CHOIBALSAN, TZ_ASIA_COLOMBO, TZ_ASIA_DAMASCUS,
    TZ_ASIA_DHAKA, TZ_ASIA_DILI, TZ_ASIA_DOHA, TZ_ASIA_DUBAI, TZ_ASIA_DUSHANBE, TZ_ASIA_HANOI,
    TZ_ASIA_HONG_KONG, TZ_ASIA_HOVD, TZ_ASIA_IRKUTSK, TZ_ASIA_JAKARTA, TZ_ASIA_JAYAPURA,
    TZ_ASIA_JERUSALEM, TZ_ASIA_KABUL, TZ_ASIA_KAMCHATKA, TZ_ASIA_KARACHI, TZ_ASIA_KATHMANDU,
    TZ_ASIA_KOLKATA, TZ_ASIA_KRASNOYARSK, TZ_ASIA_KUALA_LUMPUR, TZ_ASIA_KUWAIT, TZ_ASIA_MACAU,
    TZ_ASIA_MAGADAN, TZ_ASIA_MAKASSAR, TZ_ASIA_MANILA, TZ_ASIA_MUSCAT, TZ_ASIA_OMSK, TZ_ASIA_ORAL,
    TZ_ASIA_PHNOM_PENH, TZ_ASIA_PONTIANAK, TZ_ASIA_PYONGYANG, TZ_ASIA_QOSTANAY, TZ_ASIA_QYZYLORDA,
    TZ_ASIA_RIYADH, TZ_ASIA_SAKHALIN, TZ_ASIA_SEOUL, TZ_ASIA_SHANGHAI, TZ_ASIA_SINGAPORE,
    TZ_ASIA_TAIPEI, TZ_ASIA_TASHKENT, TZ_ASIA_TBILISI, TZ_ASIA_TEHRAN, TZ_ASIA_THIMPHU,
    TZ_ASIA_TOKYO, TZ_ASIA_ULAANBAATAR, TZ_ASIA_VIENTIANE, TZ_ASIA_VLADIVOSTOK, TZ_ASIA_YAKUTSK,
    TZ_ASIA_YANGON, TZ_ASIA_YEKATERINBURG, TZ_ASIA_YEREVAN,
};
pub use europe::{
    TZ_ATLANTIC_AZORES, TZ_ATLANTIC_CANARY, TZ_ATLANTIC_CAPE_VERDE, TZ_ATLANTIC_FAROE,
    TZ_ATLANTIC_MADEIRA, TZ_ATLANTIC_REYKJAVIK, TZ_ATLANTIC_SOUTH_GEORGIA, TZ_ATLANTIC_ST_HELENA,
    TZ_ATLANTIC_STANLEY, TZ_EUROPE_AMSTERDAM, TZ_EUROPE_ANDORRA, TZ_EUROPE_ASTRAKHAN,
    TZ_EUROPE_ATHENS, TZ_EUROPE_BELGRADE, TZ_EUROPE_BERLIN, TZ_EUROPE_BRATISLAVA,
    TZ_EUROPE_BRUSSELS, TZ_EUROPE_BUCHAREST, TZ_EUROPE_BUDAPEST, TZ_EUROPE_CHISINAU,
    TZ_EUROPE_COPENHAGEN, TZ_EUROPE_DUBLIN, TZ_EUROPE_GIBRALTAR, TZ_EUROPE_HELSINKI,
    TZ_EUROPE_ISTANBUL, TZ_EUROPE_KALININGRAD, TZ_EUROPE_KIROV, TZ_EUROPE_KYIV, TZ_EUROPE_LISBON,
    TZ_EUROPE_LJUBLJANA, TZ_EUROPE_LONDON, TZ_EUROPE_LUXEMBOURG, TZ_EUROPE_MADRID, TZ_EUROPE_MALTA,
    TZ_EUROPE_MINSK, TZ_EUROPE_MONACO, TZ_EUROPE_MOSCOW, TZ_EUROPE_NICOSIA, TZ_EUROPE_OSLO,
    TZ_EUROPE_PARIS, TZ_EUROPE_PODGORICA, TZ_EUROPE_PRAGUE, TZ_EUROPE_RIGA, TZ_EUROPE_ROME,
    TZ_EUROPE_SAMARA, TZ_EUROPE_SAN_MARINO, TZ_EUROPE_SARAJEVO, TZ_EUROPE_SARATOV,
    TZ_EUROPE_SKOPJE, TZ_EUROPE_SOFIA, TZ_EUROPE_STOCKHOLM, TZ_EUROPE_TALLINN, TZ_EUROPE_TIRANA,
    TZ_EUROPE_ULYANOVSK, TZ_EUROPE_VATICAN, TZ_EUROPE_VIENNA, TZ_EUROPE_VILNIUS,
    TZ_EUROPE_VOLGOGRAD, TZ_EUROPE_WARSAW, TZ_EUROPE_ZAGREB, TZ_EUROPE_ZURICH,
};
pub use oceania::{
    TZ_AUSTRALIA_ADELAIDE, TZ_AUSTRALIA_BRISBANE, TZ_AUSTRALIA_BROKEN_HILL, TZ_AUSTRALIA_DARWIN,
    TZ_AUSTRALIA_EUCLA, TZ_AUSTRALIA_HOBART, TZ_AUSTRALIA_LORD_HOWE, TZ_AUSTRALIA_MELBOURNE,
    TZ_AUSTRALIA_PERTH, TZ_AUSTRALIA_SYDNEY, TZ_PACIFIC_APIA, TZ_PACIFIC_AUCKLAND,
    TZ_PACIFIC_BOUGAINVILLE, TZ_PACIFIC_CHATHAM, TZ_PACIFIC_CHUUK, TZ_PACIFIC_EFATE,
    TZ_PACIFIC_ENDERBURY, TZ_PACIFIC_FAKAOFO, TZ_PACIFIC_FIJI, TZ_PACIFIC_FUNAFUTI,
    TZ_PACIFIC_GALAPAGOS, TZ_PACIFIC_GAMBIER, TZ_PACIFIC_GUADALCANAL, TZ_PACIFIC_GUAM,
    TZ_PACIFIC_KANTON, TZ_PACIFIC_KIRITIMATI, TZ_PACIFIC_KOSRAE, TZ_PACIFIC_KWAJALEIN,
    TZ_PACIFIC_MAJURO, TZ_PACIFIC_MARQUESAS, TZ_PACIFIC_NAURU, TZ_PACIFIC_NIUE, TZ_PACIFIC_NORFOLK,
    TZ_PACIFIC_NOUMEA, TZ_PACIFIC_PAGO_PAGO, TZ_PACIFIC_PALAU, TZ_PACIFIC_PITCAIRN,
    TZ_PACIFIC_POHNPEI, TZ_PACIFIC_PORT_MORESBY, TZ_PACIFIC_RAROTONGA, TZ_PACIFIC_SAIPAN,
    TZ_PACIFIC_TAHITI, TZ_PACIFIC_TAHITI_DUP, TZ_PACIFIC_TARAWA, TZ_PACIFIC_TONGATAPU,
    TZ_PACIFIC_WAKE, TZ_PACIFIC_WALLIS, TZ_PACIFIC_YAP,
};
pub use other::{
    TZ_ANTARCTICA_CASEY, TZ_ANTARCTICA_DAVIS, TZ_ANTARCTICA_DUMONTDURVILLE, TZ_ANTARCTICA_MAWSON,
    TZ_ANTARCTICA_MCMURDO, TZ_ANTARCTICA_PALMER, TZ_ANTARCTICA_ROTHERA, TZ_ANTARCTICA_SOUTH_POLE,
    TZ_ANTARCTICA_SYOWA, TZ_ANTARCTICA_TROLL, TZ_ANTARCTICA_VOSTOK, TZ_ETC_UTC, TZ_INDIAN_CHAGOS,
    TZ_INDIAN_MALDIVES,
};
