use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const AMERICAS_PROFILES: &[RegionProfile] = &[
    RegionProfile {
        country_code: "US",
        data_region: DataRegion::Us,
        legal_jurisdiction: LegalJurisdiction::Ccpa,
        primary_timezone: TZ_AMERICA_NEW_YORK,
        timezones: &[
            TZ_AMERICA_NEW_YORK,
            TZ_AMERICA_CHICAGO,
            TZ_AMERICA_DENVER,
            TZ_AMERICA_PHOENIX,
            TZ_AMERICA_LOS_ANGELES,
            TZ_AMERICA_ANCHORAGE,
            TZ_AMERICA_ADAK,
            TZ_AMERICA_HONOLULU,
            TZ_AMERICA_JUNEAU,
            TZ_AMERICA_NOME,
            TZ_AMERICA_METLAKATLA,
            TZ_AMERICA_SITKA,
            TZ_AMERICA_YAKUTAT,
            TZ_AMERICA_BOISE,
            TZ_AMERICA_INDIANA_INDIANAPOLIS,
        ],
        sub_region: None,
        display_name: Some("United States"),
    },
    RegionProfile {
        country_code: "CA",
        data_region: DataRegion::Us,
        legal_jurisdiction: LegalJurisdiction::Pipeda,
        primary_timezone: TZ_AMERICA_TORONTO,
        timezones: &[
            TZ_AMERICA_TORONTO,
            TZ_AMERICA_VANCOUVER,
            TZ_AMERICA_EDMONTON,
            TZ_AMERICA_WINNIPEG,
            TZ_AMERICA_HALIFAX,
            TZ_AMERICA_ST_JOHNS,
            TZ_AMERICA_GOOSE_BAY,
            TZ_AMERICA_BLANC_SABLON,
            TZ_AMERICA_WHITEHORSE,
            TZ_AMERICA_DAWSON,
            TZ_AMERICA_CRESTON,
            TZ_AMERICA_FORT_NELSON,
            TZ_AMERICA_RESOLUTE,
            TZ_AMERICA_RANKIN_INLET,
            TZ_AMERICA_CAMBRIDGE_BAY,
            TZ_AMERICA_IQALUIT,
            TZ_AMERICA_INUVIK,
            TZ_AMERICA_YELLOWKNIFE,
            TZ_AMERICA_REGINA,
        ],
        sub_region: None,
        display_name: Some("Canada"),
    },
    RegionProfile {
        country_code: "MX",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_MEXICO_CITY,
        timezones: &[
            TZ_AMERICA_MEXICO_CITY,
            TZ_AMERICA_CANCUN,
            TZ_AMERICA_MERIDA,
            TZ_AMERICA_MONTERREY,
            TZ_AMERICA_CHIHUAHUA,
            TZ_AMERICA_HERMOSILLO,
            TZ_AMERICA_MAZATLAN,
            TZ_AMERICA_TIJUANA,
            TZ_AMERICA_CIUDAD_JUAREZ,
        ],
        sub_region: None,
        display_name: Some("Mexico"),
    },
    RegionProfile {
        country_code: "AR",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_ARGENTINA_BUENOS_AIRES,
        timezones: &[
            TZ_AMERICA_ARGENTINA_BUENOS_AIRES,
            TZ_AMERICA_ARGENTINA_MENDOZA,
            TZ_AMERICA_ARGENTINA_USHUAIA,
            TZ_AMERICA_ARGENTINA_RIO_GALLEGOS,
        ],
        sub_region: None,
        display_name: Some("Argentina"),
    },
    RegionProfile {
        country_code: "BO",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_LA_PAZ,
        timezones: &[TZ_AMERICA_LA_PAZ],
        sub_region: None,
        display_name: Some("Bolivia"),
    },
    RegionProfile {
        country_code: "BR",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Lgpd,
        primary_timezone: TZ_AMERICA_SAO_PAULO,
        timezones: &[
            TZ_AMERICA_SAO_PAULO,
            TZ_AMERICA_NORONHA,
            TZ_AMERICA_MANAUS,
            TZ_AMERICA_RIO_BRANCO,
            TZ_AMERICA_EIRUNEPE,
            TZ_AMERICA_BOA_VISTA,
            TZ_AMERICA_CAMPO_GRANDE,
            TZ_AMERICA_CUIABA,
            TZ_AMERICA_PORTO_VELHO,
            TZ_AMERICA_BELEM,
            TZ_AMERICA_FORTALEZA,
            TZ_AMERICA_ARAGUAINA,
            TZ_AMERICA_RECIFE,
            TZ_AMERICA_BAHIA,
            TZ_AMERICA_MACEIO,
            TZ_AMERICA_SANTAREM,
        ],
        sub_region: None,
        display_name: Some("Brazil"),
    },
    RegionProfile {
        country_code: "CL",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_SANTIAGO,
        timezones: &[
            TZ_AMERICA_SANTIAGO,
            TZ_AMERICA_PUNTA_ARENAS,
            TZ_AMERICA_EASTER,
        ],
        sub_region: None,
        display_name: Some("Chile"),
    },
    RegionProfile {
        country_code: "CO",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_BOGOTA,
        timezones: &[TZ_AMERICA_BOGOTA],
        sub_region: None,
        display_name: Some("Colombia"),
    },
    RegionProfile {
        country_code: "CR",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_COSTA_RICA,
        timezones: &[TZ_AMERICA_COSTA_RICA],
        sub_region: None,
        display_name: Some("Costa Rica"),
    },
    RegionProfile {
        country_code: "CU",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_HAVANA,
        timezones: &[TZ_AMERICA_HAVANA],
        sub_region: None,
        display_name: Some("Cuba"),
    },
    RegionProfile {
        country_code: "DO",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_SANTO_DOMINGO,
        timezones: &[TZ_AMERICA_SANTO_DOMINGO],
        sub_region: None,
        display_name: Some("Dominican Republic"),
    },
    RegionProfile {
        country_code: "EC",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_GUAYAQUIL,
        timezones: &[TZ_AMERICA_GUAYAQUIL, TZ_PACIFIC_GALAPAGOS],
        sub_region: None,
        display_name: Some("Ecuador"),
    },
    RegionProfile {
        country_code: "SV",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_EL_SALVADOR,
        timezones: &[TZ_AMERICA_EL_SALVADOR],
        sub_region: None,
        display_name: Some("El Salvador"),
    },
    RegionProfile {
        country_code: "GT",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_GUATEMALA,
        timezones: &[TZ_AMERICA_GUATEMALA],
        sub_region: None,
        display_name: Some("Guatemala"),
    },
    RegionProfile {
        country_code: "GY",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_GUYANA,
        timezones: &[TZ_AMERICA_GUYANA],
        sub_region: None,
        display_name: Some("Guyana"),
    },
    RegionProfile {
        country_code: "HT",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_PORT_AU_PRINCE,
        timezones: &[TZ_AMERICA_PORT_AU_PRINCE],
        sub_region: None,
        display_name: Some("Haiti"),
    },
    RegionProfile {
        country_code: "HN",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_TEGUCIGALPA,
        timezones: &[TZ_AMERICA_TEGUCIGALPA],
        sub_region: None,
        display_name: Some("Honduras"),
    },
    RegionProfile {
        country_code: "JM",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_JAMAICA,
        timezones: &[TZ_AMERICA_JAMAICA],
        sub_region: None,
        display_name: Some("Jamaica"),
    },
    RegionProfile {
        country_code: "NI",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_MANAGUA,
        timezones: &[TZ_AMERICA_MANAGUA],
        sub_region: None,
        display_name: Some("Nicaragua"),
    },
    RegionProfile {
        country_code: "PA",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_PANAMA,
        timezones: &[TZ_AMERICA_PANAMA],
        sub_region: None,
        display_name: Some("Panama"),
    },
    RegionProfile {
        country_code: "PY",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_ASUNCION,
        timezones: &[TZ_AMERICA_ASUNCION],
        sub_region: None,
        display_name: Some("Paraguay"),
    },
    RegionProfile {
        country_code: "PE",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_LIMA,
        timezones: &[TZ_AMERICA_LIMA],
        sub_region: None,
        display_name: Some("Peru"),
    },
    RegionProfile {
        country_code: "PR",
        data_region: DataRegion::Us,
        legal_jurisdiction: LegalJurisdiction::Ccpa,
        primary_timezone: TZ_AMERICA_PUERTO_RICO,
        timezones: &[TZ_AMERICA_PUERTO_RICO],
        sub_region: Some("United States"),
        display_name: Some("Puerto Rico"),
    },
    RegionProfile {
        country_code: "SR",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_PARAMARIBO,
        timezones: &[TZ_AMERICA_PARAMARIBO],
        sub_region: None,
        display_name: Some("Suriname"),
    },
    RegionProfile {
        country_code: "TT",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_PORT_OF_SPAIN,
        timezones: &[TZ_AMERICA_PORT_OF_SPAIN],
        sub_region: None,
        display_name: Some("Trinidad and Tobago"),
    },
    RegionProfile {
        country_code: "UY",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_MONTEVIDEO,
        timezones: &[TZ_AMERICA_MONTEVIDEO],
        sub_region: None,
        display_name: Some("Uruguay"),
    },
    RegionProfile {
        country_code: "VE",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_CARACAS,
        timezones: &[TZ_AMERICA_CARACAS],
        sub_region: None,
        display_name: Some("Venezuela"),
    },
    RegionProfile {
        country_code: "BZ",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_BELIZE,
        timezones: &[TZ_AMERICA_BELIZE],
        sub_region: None,
        display_name: Some("Belize"),
    },
    RegionProfile {
        country_code: "BS",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_NASSAU,
        timezones: &[TZ_AMERICA_NASSAU],
        sub_region: None,
        display_name: Some("Bahamas"),
    },
    RegionProfile {
        country_code: "BB",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_BARBADOS,
        timezones: &[TZ_AMERICA_BARBADOS],
        sub_region: None,
        display_name: Some("Barbados"),
    },
    RegionProfile {
        country_code: "AG",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_ANTIGUA,
        timezones: &[TZ_AMERICA_ANTIGUA],
        sub_region: None,
        display_name: Some("Antigua and Barbuda"),
    },
    RegionProfile {
        country_code: "DM",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_DOMINICA,
        timezones: &[TZ_AMERICA_DOMINICA],
        sub_region: None,
        display_name: Some("Dominica"),
    },
    RegionProfile {
        country_code: "GD",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_GRENADA,
        timezones: &[TZ_AMERICA_GRENADA],
        sub_region: None,
        display_name: Some("Grenada"),
    },
    RegionProfile {
        country_code: "KN",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_ST_KITTS,
        timezones: &[TZ_AMERICA_ST_KITTS],
        sub_region: None,
        display_name: Some("Saint Kitts and Nevis"),
    },
    RegionProfile {
        country_code: "LC",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_ST_LUCIA,
        timezones: &[TZ_AMERICA_ST_LUCIA],
        sub_region: None,
        display_name: Some("Saint Lucia"),
    },
    RegionProfile {
        country_code: "VC",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_ST_VINCENT,
        timezones: &[TZ_AMERICA_ST_VINCENT],
        sub_region: None,
        display_name: Some("Saint Vincent and the Grenadines"),
    },
    RegionProfile {
        country_code: "VI",
        data_region: DataRegion::Us,
        legal_jurisdiction: LegalJurisdiction::Ccpa,
        primary_timezone: TZ_AMERICA_ST_THOMAS,
        timezones: &[TZ_AMERICA_ST_THOMAS],
        sub_region: Some("United States"),
        display_name: Some("U.S. Virgin Islands"),
    },
    RegionProfile {
        country_code: "GU",
        data_region: DataRegion::Us,
        legal_jurisdiction: LegalJurisdiction::Ccpa,
        primary_timezone: TZ_PACIFIC_GUAM,
        timezones: &[TZ_PACIFIC_GUAM],
        sub_region: Some("United States"),
        display_name: Some("Guam"),
    },
    RegionProfile {
        country_code: "MP",
        data_region: DataRegion::Us,
        legal_jurisdiction: LegalJurisdiction::Ccpa,
        primary_timezone: TZ_PACIFIC_SAIPAN,
        timezones: &[TZ_PACIFIC_SAIPAN],
        sub_region: Some("United States"),
        display_name: Some("Northern Mariana Islands"),
    },
    RegionProfile {
        country_code: "AS",
        data_region: DataRegion::Us,
        legal_jurisdiction: LegalJurisdiction::Ccpa,
        primary_timezone: TZ_PACIFIC_PAGO_PAGO,
        timezones: &[TZ_PACIFIC_PAGO_PAGO],
        sub_region: Some("United States"),
        display_name: Some("American Samoa"),
    },
    RegionProfile {
        country_code: "AI",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_ANGUILLA,
        timezones: &[TZ_AMERICA_ANGUILLA],
        sub_region: Some("United Kingdom"),
        display_name: Some("Anguilla"),
    },
    RegionProfile {
        country_code: "BM",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_HAMILTON,
        timezones: &[TZ_AMERICA_HAMILTON],
        sub_region: Some("United Kingdom"),
        display_name: Some("Bermuda"),
    },
    RegionProfile {
        country_code: "KY",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_PANAMA,
        timezones: &[TZ_AMERICA_PANAMA],
        sub_region: Some("United Kingdom"),
        display_name: Some("Cayman Islands"),
    },
    RegionProfile {
        country_code: "FK",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_ATLANTIC_STANLEY,
        timezones: &[TZ_ATLANTIC_STANLEY],
        sub_region: Some("United Kingdom"),
        display_name: Some("Falkland Islands"),
    },
    RegionProfile {
        country_code: "VG",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_TORTOLA,
        timezones: &[TZ_AMERICA_TORTOLA],
        sub_region: Some("United Kingdom"),
        display_name: Some("British Virgin Islands"),
    },
    RegionProfile {
        country_code: "TC",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_GRAND_TURK,
        timezones: &[TZ_AMERICA_GRAND_TURK],
        sub_region: Some("United Kingdom"),
        display_name: Some("Turks and Caicos Islands"),
    },
    RegionProfile {
        country_code: "MS",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_MONTSERRAT,
        timezones: &[TZ_AMERICA_MONTSERRAT],
        sub_region: Some("United Kingdom"),
        display_name: Some("Montserrat"),
    },
    RegionProfile {
        country_code: "AW",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_ARUBA,
        timezones: &[TZ_AMERICA_ARUBA],
        sub_region: Some("Netherlands"),
        display_name: Some("Aruba"),
    },
    RegionProfile {
        country_code: "CW",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_CURACAO,
        timezones: &[TZ_AMERICA_CURACAO],
        sub_region: Some("Netherlands"),
        display_name: Some("Curacao"),
    },
    RegionProfile {
        country_code: "SX",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_MARIGOT,
        timezones: &[TZ_AMERICA_MARIGOT],
        sub_region: Some("Netherlands"),
        display_name: Some("Sint Maarten"),
    },
    RegionProfile {
        country_code: "BQ",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_KRALENDIJK,
        timezones: &[TZ_AMERICA_KRALENDIJK],
        sub_region: Some("Netherlands"),
        display_name: Some("Caribbean Netherlands"),
    },
];
