use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const EUROPE_PROFILES_PART_1: &[RegionProfile] = &[
    RegionProfile {
        country_code: "AT",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_VIENNA,
        timezones: &[TZ_EUROPE_VIENNA],
        sub_region: None,
        display_name: Some("Austria"),
    },
    RegionProfile {
        country_code: "BE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BRUSSELS,
        timezones: &[TZ_EUROPE_BRUSSELS],
        sub_region: None,
        display_name: Some("Belgium"),
    },
    RegionProfile {
        country_code: "BG",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_SOFIA,
        timezones: &[TZ_EUROPE_SOFIA],
        sub_region: None,
        display_name: Some("Bulgaria"),
    },
    RegionProfile {
        country_code: "HR",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_ZAGREB,
        timezones: &[TZ_EUROPE_ZAGREB],
        sub_region: None,
        display_name: Some("Croatia"),
    },
    RegionProfile {
        country_code: "CY",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_NICOSIA,
        timezones: &[TZ_EUROPE_NICOSIA],
        sub_region: None,
        display_name: Some("Cyprus"),
    },
    RegionProfile {
        country_code: "CZ",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_PRAGUE,
        timezones: &[TZ_EUROPE_PRAGUE],
        sub_region: None,
        display_name: Some("Czech Republic"),
    },
    RegionProfile {
        country_code: "DK",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_COPENHAGEN,
        timezones: &[TZ_EUROPE_COPENHAGEN],
        sub_region: None,
        display_name: Some("Denmark"),
    },
    RegionProfile {
        country_code: "EE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_TALLINN,
        timezones: &[TZ_EUROPE_TALLINN],
        sub_region: None,
        display_name: Some("Estonia"),
    },
    RegionProfile {
        country_code: "FI",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_HELSINKI,
        timezones: &[TZ_EUROPE_HELSINKI],
        sub_region: None,
        display_name: Some("Finland"),
    },
    RegionProfile {
        country_code: "FR",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_PARIS,
        timezones: &[TZ_EUROPE_PARIS],
        sub_region: None,
        display_name: Some("France"),
    },
    RegionProfile {
        country_code: "DE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BERLIN,
        timezones: &[TZ_EUROPE_BERLIN],
        sub_region: None,
        display_name: Some("Germany"),
    },
    RegionProfile {
        country_code: "GR",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_ATHENS,
        timezones: &[TZ_EUROPE_ATHENS],
        sub_region: None,
        display_name: Some("Greece"),
    },
    RegionProfile {
        country_code: "HU",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BUDAPEST,
        timezones: &[TZ_EUROPE_BUDAPEST],
        sub_region: None,
        display_name: Some("Hungary"),
    },
    RegionProfile {
        country_code: "IE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_DUBLIN,
        timezones: &[TZ_EUROPE_DUBLIN],
        sub_region: None,
        display_name: Some("Ireland"),
    },
    RegionProfile {
        country_code: "IT",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_ROME,
        timezones: &[TZ_EUROPE_ROME],
        sub_region: None,
        display_name: Some("Italy"),
    },
    RegionProfile {
        country_code: "LV",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_RIGA,
        timezones: &[TZ_EUROPE_RIGA],
        sub_region: None,
        display_name: Some("Latvia"),
    },
    RegionProfile {
        country_code: "LT",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_VILNIUS,
        timezones: &[TZ_EUROPE_VILNIUS],
        sub_region: None,
        display_name: Some("Lithuania"),
    },
    RegionProfile {
        country_code: "LU",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_LUXEMBOURG,
        timezones: &[TZ_EUROPE_LUXEMBOURG],
        sub_region: None,
        display_name: Some("Luxembourg"),
    },
    RegionProfile {
        country_code: "MT",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_MALTA,
        timezones: &[TZ_EUROPE_MALTA],
        sub_region: None,
        display_name: Some("Malta"),
    },
    RegionProfile {
        country_code: "NL",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_AMSTERDAM,
        timezones: &[TZ_EUROPE_AMSTERDAM],
        sub_region: None,
        display_name: Some("Netherlands"),
    },
    RegionProfile {
        country_code: "PL",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_WARSAW,
        timezones: &[TZ_EUROPE_WARSAW],
        sub_region: None,
        display_name: Some("Poland"),
    },
    RegionProfile {
        country_code: "PT",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_LISBON,
        timezones: &[TZ_EUROPE_LISBON, TZ_ATLANTIC_MADEIRA, TZ_ATLANTIC_AZORES],
        sub_region: None,
        display_name: Some("Portugal"),
    },
    RegionProfile {
        country_code: "RO",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BUCHAREST,
        timezones: &[TZ_EUROPE_BUCHAREST],
        sub_region: None,
        display_name: Some("Romania"),
    },
    RegionProfile {
        country_code: "SK",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BRATISLAVA,
        timezones: &[TZ_EUROPE_BRATISLAVA],
        sub_region: None,
        display_name: Some("Slovakia"),
    },
    RegionProfile {
        country_code: "SI",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_LJUBLJANA,
        timezones: &[TZ_EUROPE_LJUBLJANA],
        sub_region: None,
        display_name: Some("Slovenia"),
    },
];
