use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const EUROPE_PROFILES_PART_3: &[RegionProfile] = &[
    RegionProfile {
        country_code: "TR",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_EUROPE_ISTANBUL,
        timezones: &[TZ_EUROPE_ISTANBUL],
        sub_region: None,
        display_name: Some("Turkey"),
    },
    RegionProfile {
        country_code: "UA",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_KYIV,
        timezones: &[TZ_EUROPE_KYIV],
        sub_region: None,
        display_name: Some("Ukraine"),
    },
    RegionProfile {
        country_code: "XK",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BELGRADE,
        timezones: &[TZ_EUROPE_BELGRADE],
        sub_region: None,
        display_name: Some("Kosovo"),
    },
    RegionProfile {
        country_code: "FO",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_ATLANTIC_FAROE,
        timezones: &[TZ_ATLANTIC_FAROE],
        sub_region: Some("Denmark"),
        display_name: Some("Faroe Islands"),
    },
    RegionProfile {
        country_code: "GL",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_NUUK,
        timezones: &[
            TZ_AMERICA_NUUK,
            TZ_AMERICA_DANMARKSHAVN,
            TZ_AMERICA_SCORESBYSUND,
            TZ_AMERICA_THULE,
        ],
        sub_region: Some("Denmark"),
        display_name: Some("Greenland"),
    },
    RegionProfile {
        country_code: "AX",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_HELSINKI,
        timezones: &[TZ_EUROPE_HELSINKI],
        sub_region: Some("Finland"),
        display_name: Some("Aland Islands"),
    },
    RegionProfile {
        country_code: "SJ",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_OSLO,
        timezones: &[TZ_EUROPE_OSLO],
        sub_region: Some("Norway"),
        display_name: Some("Svalbard and Jan Mayen"),
    },
    RegionProfile {
        country_code: "GF",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_CAYENNE,
        timezones: &[TZ_AMERICA_CAYENNE],
        sub_region: Some("France"),
        display_name: Some("French Guiana"),
    },
    RegionProfile {
        country_code: "GP",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_GUADELOUPE,
        timezones: &[TZ_AMERICA_GUADELOUPE],
        sub_region: Some("France"),
        display_name: Some("Guadeloupe"),
    },
    RegionProfile {
        country_code: "MQ",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_MARTINIQUE,
        timezones: &[TZ_AMERICA_MARTINIQUE],
        sub_region: Some("France"),
        display_name: Some("Martinique"),
    },
    RegionProfile {
        country_code: "RE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AFRICA_REUNION,
        timezones: &[TZ_AFRICA_REUNION],
        sub_region: Some("France"),
        display_name: Some("Reunion"),
    },
    RegionProfile {
        country_code: "YT",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AFRICA_MAYOTTE,
        timezones: &[TZ_AFRICA_MAYOTTE],
        sub_region: Some("France"),
        display_name: Some("Mayotte"),
    },
    RegionProfile {
        country_code: "BL",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_ST_BARTHELEMY,
        timezones: &[TZ_AMERICA_ST_BARTHELEMY],
        sub_region: Some("France"),
        display_name: Some("Saint Barthelemy"),
    },
    RegionProfile {
        country_code: "MF",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_MARIGOT,
        timezones: &[TZ_AMERICA_MARIGOT],
        sub_region: Some("France"),
        display_name: Some("Saint Martin"),
    },
    RegionProfile {
        country_code: "PM",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_MIQUELON,
        timezones: &[TZ_AMERICA_MIQUELON],
        sub_region: Some("France"),
        display_name: Some("Saint Pierre and Miquelon"),
    },
    RegionProfile {
        country_code: "WF",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_PACIFIC_WALLIS,
        timezones: &[TZ_PACIFIC_WALLIS],
        sub_region: Some("France"),
        display_name: Some("Wallis and Futuna"),
    },
    RegionProfile {
        country_code: "PF",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_PACIFIC_TAHITI,
        timezones: &[TZ_PACIFIC_TAHITI, TZ_PACIFIC_GAMBIER, TZ_PACIFIC_MARQUESAS],
        sub_region: Some("France"),
        display_name: Some("French Polynesia"),
    },
    RegionProfile {
        country_code: "NC",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_PACIFIC_NOUMEA,
        timezones: &[TZ_PACIFIC_NOUMEA],
        sub_region: Some("France"),
        display_name: Some("New Caledonia"),
    },
    RegionProfile {
        country_code: "TF",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AFRICA_REUNION,
        timezones: &[TZ_AFRICA_REUNION],
        sub_region: Some("France"),
        display_name: Some("French Southern Territories"),
    },
    RegionProfile {
        country_code: "RU",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_EUROPE_MOSCOW,
        timezones: &[
            TZ_EUROPE_MOSCOW,
            TZ_EUROPE_KALININGRAD,
            TZ_EUROPE_SAMARA,
            TZ_EUROPE_ASTRAKHAN,
            TZ_EUROPE_ULYANOVSK,
            TZ_EUROPE_SARATOV,
            TZ_EUROPE_KIROV,
            TZ_EUROPE_VOLGOGRAD,
            TZ_ASIA_YEKATERINBURG,
            TZ_ASIA_OMSK,
            TZ_ASIA_KRASNOYARSK,
            TZ_ASIA_IRKUTSK,
            TZ_ASIA_YAKUTSK,
            TZ_ASIA_VLADIVOSTOK,
            TZ_ASIA_MAGADAN,
            TZ_ASIA_KAMCHATKA,
            TZ_ASIA_ANADYR,
            TZ_ASIA_SAKHALIN,
        ],
        sub_region: None,
        display_name: Some("Russia"),
    },
];
