use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const EUROPE_PROFILES: &[RegionProfile] = &[
    RegionProfile {
        country_code: "AT",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_VIENNA,
        timezones: &[TZ_EUROPE_VIENNA],
        sub_region: None,
        display_name: Some("Austria"),
    },
    RegionProfile {
        country_code: "BE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BRUSSELS,
        timezones: &[TZ_EUROPE_BRUSSELS],
        sub_region: None,
        display_name: Some("Belgium"),
    },
    RegionProfile {
        country_code: "BG",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_SOFIA,
        timezones: &[TZ_EUROPE_SOFIA],
        sub_region: None,
        display_name: Some("Bulgaria"),
    },
    RegionProfile {
        country_code: "HR",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_ZAGREB,
        timezones: &[TZ_EUROPE_ZAGREB],
        sub_region: None,
        display_name: Some("Croatia"),
    },
    RegionProfile {
        country_code: "CY",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_NICOSIA,
        timezones: &[TZ_EUROPE_NICOSIA],
        sub_region: None,
        display_name: Some("Cyprus"),
    },
    RegionProfile {
        country_code: "CZ",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_PRAGUE,
        timezones: &[TZ_EUROPE_PRAGUE],
        sub_region: None,
        display_name: Some("Czech Republic"),
    },
    RegionProfile {
        country_code: "DK",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_COPENHAGEN,
        timezones: &[TZ_EUROPE_COPENHAGEN],
        sub_region: None,
        display_name: Some("Denmark"),
    },
    RegionProfile {
        country_code: "EE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_TALLINN,
        timezones: &[TZ_EUROPE_TALLINN],
        sub_region: None,
        display_name: Some("Estonia"),
    },
    RegionProfile {
        country_code: "FI",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_HELSINKI,
        timezones: &[TZ_EUROPE_HELSINKI],
        sub_region: None,
        display_name: Some("Finland"),
    },
    RegionProfile {
        country_code: "FR",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_PARIS,
        timezones: &[TZ_EUROPE_PARIS],
        sub_region: None,
        display_name: Some("France"),
    },
    RegionProfile {
        country_code: "DE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BERLIN,
        timezones: &[TZ_EUROPE_BERLIN],
        sub_region: None,
        display_name: Some("Germany"),
    },
    RegionProfile {
        country_code: "GR",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_ATHENS,
        timezones: &[TZ_EUROPE_ATHENS],
        sub_region: None,
        display_name: Some("Greece"),
    },
    RegionProfile {
        country_code: "HU",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BUDAPEST,
        timezones: &[TZ_EUROPE_BUDAPEST],
        sub_region: None,
        display_name: Some("Hungary"),
    },
    RegionProfile {
        country_code: "IE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_DUBLIN,
        timezones: &[TZ_EUROPE_DUBLIN],
        sub_region: None,
        display_name: Some("Ireland"),
    },
    RegionProfile {
        country_code: "IT",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_ROME,
        timezones: &[TZ_EUROPE_ROME],
        sub_region: None,
        display_name: Some("Italy"),
    },
    RegionProfile {
        country_code: "LV",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_RIGA,
        timezones: &[TZ_EUROPE_RIGA],
        sub_region: None,
        display_name: Some("Latvia"),
    },
    RegionProfile {
        country_code: "LT",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_VILNIUS,
        timezones: &[TZ_EUROPE_VILNIUS],
        sub_region: None,
        display_name: Some("Lithuania"),
    },
    RegionProfile {
        country_code: "LU",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_LUXEMBOURG,
        timezones: &[TZ_EUROPE_LUXEMBOURG],
        sub_region: None,
        display_name: Some("Luxembourg"),
    },
    RegionProfile {
        country_code: "MT",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_MALTA,
        timezones: &[TZ_EUROPE_MALTA],
        sub_region: None,
        display_name: Some("Malta"),
    },
    RegionProfile {
        country_code: "NL",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_AMSTERDAM,
        timezones: &[TZ_EUROPE_AMSTERDAM],
        sub_region: None,
        display_name: Some("Netherlands"),
    },
    RegionProfile {
        country_code: "PL",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_WARSAW,
        timezones: &[TZ_EUROPE_WARSAW],
        sub_region: None,
        display_name: Some("Poland"),
    },
    RegionProfile {
        country_code: "PT",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_LISBON,
        timezones: &[TZ_EUROPE_LISBON, TZ_ATLANTIC_MADEIRA, TZ_ATLANTIC_AZORES],
        sub_region: None,
        display_name: Some("Portugal"),
    },
    RegionProfile {
        country_code: "RO",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BUCHAREST,
        timezones: &[TZ_EUROPE_BUCHAREST],
        sub_region: None,
        display_name: Some("Romania"),
    },
    RegionProfile {
        country_code: "SK",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BRATISLAVA,
        timezones: &[TZ_EUROPE_BRATISLAVA],
        sub_region: None,
        display_name: Some("Slovakia"),
    },
    RegionProfile {
        country_code: "SI",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_LJUBLJANA,
        timezones: &[TZ_EUROPE_LJUBLJANA],
        sub_region: None,
        display_name: Some("Slovenia"),
    },
    RegionProfile {
        country_code: "ES",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_MADRID,
        timezones: &[TZ_EUROPE_MADRID, TZ_ATLANTIC_CANARY],
        sub_region: None,
        display_name: Some("Spain"),
    },
    RegionProfile {
        country_code: "SE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_STOCKHOLM,
        timezones: &[TZ_EUROPE_STOCKHOLM],
        sub_region: None,
        display_name: Some("Sweden"),
    },
    RegionProfile {
        country_code: "IS",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_ATLANTIC_REYKJAVIK,
        timezones: &[TZ_ATLANTIC_REYKJAVIK],
        sub_region: None,
        display_name: Some("Iceland"),
    },
    RegionProfile {
        country_code: "LI",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_ZURICH,
        timezones: &[TZ_EUROPE_ZURICH],
        sub_region: None,
        display_name: Some("Liechtenstein"),
    },
    RegionProfile {
        country_code: "NO",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_OSLO,
        timezones: &[TZ_EUROPE_OSLO],
        sub_region: None,
        display_name: Some("Norway"),
    },
    RegionProfile {
        country_code: "CH",
        data_region: DataRegion::Ch,
        legal_jurisdiction: LegalJurisdiction::Nfdap,
        primary_timezone: TZ_EUROPE_ZURICH,
        timezones: &[TZ_EUROPE_ZURICH],
        sub_region: None,
        display_name: Some("Switzerland"),
    },
    RegionProfile {
        country_code: "GB",
        data_region: DataRegion::Uk,
        legal_jurisdiction: LegalJurisdiction::UkGdpr,
        primary_timezone: TZ_EUROPE_LONDON,
        timezones: &[TZ_EUROPE_LONDON],
        sub_region: None,
        display_name: Some("United Kingdom"),
    },
    RegionProfile {
        country_code: "AL",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_TIRANA,
        timezones: &[TZ_EUROPE_TIRANA],
        sub_region: None,
        display_name: Some("Albania"),
    },
    RegionProfile {
        country_code: "AD",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_ANDORRA,
        timezones: &[TZ_EUROPE_ANDORRA],
        sub_region: None,
        display_name: Some("Andorra"),
    },
    RegionProfile {
        country_code: "AM",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_YEREVAN,
        timezones: &[TZ_ASIA_YEREVAN],
        sub_region: None,
        display_name: Some("Armenia"),
    },
    RegionProfile {
        country_code: "AZ",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_BAKU,
        timezones: &[TZ_ASIA_BAKU],
        sub_region: None,
        display_name: Some("Azerbaijan"),
    },
    RegionProfile {
        country_code: "BY",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_EUROPE_MINSK,
        timezones: &[TZ_EUROPE_MINSK],
        sub_region: None,
        display_name: Some("Belarus"),
    },
    RegionProfile {
        country_code: "BA",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_SARAJEVO,
        timezones: &[TZ_EUROPE_SARAJEVO],
        sub_region: None,
        display_name: Some("Bosnia and Herzegovina"),
    },
    RegionProfile {
        country_code: "GE",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_TBILISI,
        timezones: &[TZ_ASIA_TBILISI],
        sub_region: None,
        display_name: Some("Georgia"),
    },
    RegionProfile {
        country_code: "GI",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_GIBRALTAR,
        timezones: &[TZ_EUROPE_GIBRALTAR],
        sub_region: None,
        display_name: Some("Gibraltar"),
    },
    RegionProfile {
        country_code: "GG",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_LONDON,
        timezones: &[TZ_EUROPE_LONDON],
        sub_region: Some("Crown Dependency"),
        display_name: Some("Guernsey"),
    },
    RegionProfile {
        country_code: "VA",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_VATICAN,
        timezones: &[TZ_EUROPE_VATICAN],
        sub_region: None,
        display_name: Some("Vatican City"),
    },
    RegionProfile {
        country_code: "IM",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_LONDON,
        timezones: &[TZ_EUROPE_LONDON],
        sub_region: Some("Crown Dependency"),
        display_name: Some("Isle of Man"),
    },
    RegionProfile {
        country_code: "JE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_LONDON,
        timezones: &[TZ_EUROPE_LONDON],
        sub_region: Some("Crown Dependency"),
        display_name: Some("Jersey"),
    },
    RegionProfile {
        country_code: "MC",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_MONACO,
        timezones: &[TZ_EUROPE_MONACO],
        sub_region: None,
        display_name: Some("Monaco"),
    },
    RegionProfile {
        country_code: "ME",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_PODGORICA,
        timezones: &[TZ_EUROPE_PODGORICA],
        sub_region: None,
        display_name: Some("Montenegro"),
    },
    RegionProfile {
        country_code: "MK",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_SKOPJE,
        timezones: &[TZ_EUROPE_SKOPJE],
        sub_region: None,
        display_name: Some("North Macedonia"),
    },
    RegionProfile {
        country_code: "MD",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_CHISINAU,
        timezones: &[TZ_EUROPE_CHISINAU],
        sub_region: None,
        display_name: Some("Moldova"),
    },
    RegionProfile {
        country_code: "RS",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BELGRADE,
        timezones: &[TZ_EUROPE_BELGRADE],
        sub_region: None,
        display_name: Some("Serbia"),
    },
    RegionProfile {
        country_code: "SM",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_SAN_MARINO,
        timezones: &[TZ_EUROPE_SAN_MARINO],
        sub_region: None,
        display_name: Some("San Marino"),
    },
    RegionProfile {
        country_code: "TR",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_EUROPE_ISTANBUL,
        timezones: &[TZ_EUROPE_ISTANBUL],
        sub_region: None,
        display_name: Some("Turkey"),
    },
    RegionProfile {
        country_code: "UA",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_KYIV,
        timezones: &[TZ_EUROPE_KYIV],
        sub_region: None,
        display_name: Some("Ukraine"),
    },
    RegionProfile {
        country_code: "XK",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BELGRADE,
        timezones: &[TZ_EUROPE_BELGRADE],
        sub_region: None,
        display_name: Some("Kosovo"),
    },
    RegionProfile {
        country_code: "FO",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_ATLANTIC_FAROE,
        timezones: &[TZ_ATLANTIC_FAROE],
        sub_region: Some("Denmark"),
        display_name: Some("Faroe Islands"),
    },
    RegionProfile {
        country_code: "GL",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_NUUK,
        timezones: &[
            TZ_AMERICA_NUUK,
            TZ_AMERICA_DANMARKSHAVN,
            TZ_AMERICA_SCORESBYSUND,
            TZ_AMERICA_THULE,
        ],
        sub_region: Some("Denmark"),
        display_name: Some("Greenland"),
    },
    RegionProfile {
        country_code: "AX",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_HELSINKI,
        timezones: &[TZ_EUROPE_HELSINKI],
        sub_region: Some("Finland"),
        display_name: Some("Aland Islands"),
    },
    RegionProfile {
        country_code: "SJ",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_OSLO,
        timezones: &[TZ_EUROPE_OSLO],
        sub_region: Some("Norway"),
        display_name: Some("Svalbard and Jan Mayen"),
    },
    RegionProfile {
        country_code: "GF",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_CAYENNE,
        timezones: &[TZ_AMERICA_CAYENNE],
        sub_region: Some("France"),
        display_name: Some("French Guiana"),
    },
    RegionProfile {
        country_code: "GP",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_GUADELOUPE,
        timezones: &[TZ_AMERICA_GUADELOUPE],
        sub_region: Some("France"),
        display_name: Some("Guadeloupe"),
    },
    RegionProfile {
        country_code: "MQ",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_MARTINIQUE,
        timezones: &[TZ_AMERICA_MARTINIQUE],
        sub_region: Some("France"),
        display_name: Some("Martinique"),
    },
    RegionProfile {
        country_code: "RE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AFRICA_REUNION,
        timezones: &[TZ_AFRICA_REUNION],
        sub_region: Some("France"),
        display_name: Some("Reunion"),
    },
    RegionProfile {
        country_code: "YT",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AFRICA_MAYOTTE,
        timezones: &[TZ_AFRICA_MAYOTTE],
        sub_region: Some("France"),
        display_name: Some("Mayotte"),
    },
    RegionProfile {
        country_code: "BL",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_ST_BARTHELEMY,
        timezones: &[TZ_AMERICA_ST_BARTHELEMY],
        sub_region: Some("France"),
        display_name: Some("Saint Barthelemy"),
    },
    RegionProfile {
        country_code: "MF",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_MARIGOT,
        timezones: &[TZ_AMERICA_MARIGOT],
        sub_region: Some("France"),
        display_name: Some("Saint Martin"),
    },
    RegionProfile {
        country_code: "PM",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_MIQUELON,
        timezones: &[TZ_AMERICA_MIQUELON],
        sub_region: Some("France"),
        display_name: Some("Saint Pierre and Miquelon"),
    },
    RegionProfile {
        country_code: "WF",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_PACIFIC_WALLIS,
        timezones: &[TZ_PACIFIC_WALLIS],
        sub_region: Some("France"),
        display_name: Some("Wallis and Futuna"),
    },
    RegionProfile {
        country_code: "PF",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_PACIFIC_TAHITI,
        timezones: &[TZ_PACIFIC_TAHITI, TZ_PACIFIC_GAMBIER, TZ_PACIFIC_MARQUESAS],
        sub_region: Some("France"),
        display_name: Some("French Polynesia"),
    },
    RegionProfile {
        country_code: "NC",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_PACIFIC_NOUMEA,
        timezones: &[TZ_PACIFIC_NOUMEA],
        sub_region: Some("France"),
        display_name: Some("New Caledonia"),
    },
    RegionProfile {
        country_code: "TF",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AFRICA_REUNION,
        timezones: &[TZ_AFRICA_REUNION],
        sub_region: Some("France"),
        display_name: Some("French Southern Territories"),
    },
    RegionProfile {
        country_code: "RU",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_EUROPE_MOSCOW,
        timezones: &[
            TZ_EUROPE_MOSCOW,
            TZ_EUROPE_KALININGRAD,
            TZ_EUROPE_SAMARA,
            TZ_EUROPE_ASTRAKHAN,
            TZ_EUROPE_ULYANOVSK,
            TZ_EUROPE_SARATOV,
            TZ_EUROPE_KIROV,
            TZ_EUROPE_VOLGOGRAD,
            TZ_ASIA_YEKATERINBURG,
            TZ_ASIA_OMSK,
            TZ_ASIA_KRASNOYARSK,
            TZ_ASIA_IRKUTSK,
            TZ_ASIA_YAKUTSK,
            TZ_ASIA_VLADIVOSTOK,
            TZ_ASIA_MAGADAN,
            TZ_ASIA_KAMCHATKA,
            TZ_ASIA_ANADYR,
            TZ_ASIA_SAKHALIN,
        ],
        sub_region: None,
        display_name: Some("Russia"),
    },
];
