use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const AMERICAS_PROFILES_PART_3: &[RegionProfile] = &[
    RegionProfile {
        country_code: "KY",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_PANAMA,
        timezones: &[TZ_AMERICA_PANAMA],
        sub_region: Some("United Kingdom"),
        display_name: Some("Cayman Islands"),
    },
    RegionProfile {
        country_code: "FK",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_ATLANTIC_STANLEY,
        timezones: &[TZ_ATLANTIC_STANLEY],
        sub_region: Some("United Kingdom"),
        display_name: Some("Falkland Islands"),
    },
    RegionProfile {
        country_code: "VG",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_TORTOLA,
        timezones: &[TZ_AMERICA_TORTOLA],
        sub_region: Some("United Kingdom"),
        display_name: Some("British Virgin Islands"),
    },
    RegionProfile {
        country_code: "TC",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_GRAND_TURK,
        timezones: &[TZ_AMERICA_GRAND_TURK],
        sub_region: Some("United Kingdom"),
        display_name: Some("Turks and Caicos Islands"),
    },
    RegionProfile {
        country_code: "MS",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_MONTSERRAT,
        timezones: &[TZ_AMERICA_MONTSERRAT],
        sub_region: Some("United Kingdom"),
        display_name: Some("Montserrat"),
    },
    RegionProfile {
        country_code: "AW",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_ARUBA,
        timezones: &[TZ_AMERICA_ARUBA],
        sub_region: Some("Netherlands"),
        display_name: Some("Aruba"),
    },
    RegionProfile {
        country_code: "CW",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_CURACAO,
        timezones: &[TZ_AMERICA_CURACAO],
        sub_region: Some("Netherlands"),
        display_name: Some("Curacao"),
    },
    RegionProfile {
        country_code: "SX",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_MARIGOT,
        timezones: &[TZ_AMERICA_MARIGOT],
        sub_region: Some("Netherlands"),
        display_name: Some("Sint Maarten"),
    },
    RegionProfile {
        country_code: "BQ",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_KRALENDIJK,
        timezones: &[TZ_AMERICA_KRALENDIJK],
        sub_region: Some("Netherlands"),
        display_name: Some("Caribbean Netherlands"),
    },
];
