use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const ASIA_PACIFIC_PROFILES_PART_2: &[RegionProfile] = &[
    RegionProfile {
        country_code: "NR",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_NAURU,
        timezones: &[TZ_PACIFIC_NAURU],
        sub_region: None,
        display_name: Some("Nauru"),
    },
    RegionProfile {
        country_code: "NP",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_KATHMANDU,
        timezones: &[TZ_ASIA_KATHMANDU],
        sub_region: None,
        display_name: Some("Nepal"),
    },
    RegionProfile {
        country_code: "NZ",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Nzpa,
        primary_timezone: TZ_PACIFIC_AUCKLAND,
        timezones: &[TZ_PACIFIC_AUCKLAND, TZ_PACIFIC_CHATHAM],
        sub_region: None,
        display_name: Some("New Zealand"),
    },
    RegionProfile {
        country_code: "PK",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_KARACHI,
        timezones: &[TZ_ASIA_KARACHI],
        sub_region: None,
        display_name: Some("Pakistan"),
    },
    RegionProfile {
        country_code: "PW",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_PALAU,
        timezones: &[TZ_PACIFIC_PALAU],
        sub_region: None,
        display_name: Some("Palau"),
    },
    RegionProfile {
        country_code: "PG",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_PORT_MORESBY,
        timezones: &[TZ_PACIFIC_PORT_MORESBY, TZ_PACIFIC_BOUGAINVILLE],
        sub_region: None,
        display_name: Some("Papua New Guinea"),
    },
    RegionProfile {
        country_code: "PH",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_MANILA,
        timezones: &[TZ_ASIA_MANILA],
        sub_region: None,
        display_name: Some("Philippines"),
    },
    RegionProfile {
        country_code: "WS",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_APIA,
        timezones: &[TZ_PACIFIC_APIA],
        sub_region: None,
        display_name: Some("Samoa"),
    },
    RegionProfile {
        country_code: "SG",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Pdpa,
        primary_timezone: TZ_ASIA_SINGAPORE,
        timezones: &[TZ_ASIA_SINGAPORE],
        sub_region: None,
        display_name: Some("Singapore"),
    },
    RegionProfile {
        country_code: "SB",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_GUADALCANAL,
        timezones: &[TZ_PACIFIC_GUADALCANAL],
        sub_region: None,
        display_name: Some("Solomon Islands"),
    },
    RegionProfile {
        country_code: "LK",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_COLOMBO,
        timezones: &[TZ_ASIA_COLOMBO],
        sub_region: None,
        display_name: Some("Sri Lanka"),
    },
    RegionProfile {
        country_code: "TW",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_TAIPEI,
        timezones: &[TZ_ASIA_TAIPEI],
        sub_region: None,
        display_name: Some("Taiwan"),
    },
    RegionProfile {
        country_code: "TJ",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_DUSHANBE,
        timezones: &[TZ_ASIA_DUSHANBE],
        sub_region: None,
        display_name: Some("Tajikistan"),
    },
    RegionProfile {
        country_code: "TH",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Pdpa,
        primary_timezone: TZ_ASIA_BANGKOK,
        timezones: &[TZ_ASIA_BANGKOK],
        sub_region: None,
        display_name: Some("Thailand"),
    },
    RegionProfile {
        country_code: "TL",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_DILI,
        timezones: &[TZ_ASIA_DILI],
        sub_region: None,
        display_name: Some("Timor-Leste"),
    },
    RegionProfile {
        country_code: "TO",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_TONGATAPU,
        timezones: &[TZ_PACIFIC_TONGATAPU],
        sub_region: None,
        display_name: Some("Tonga"),
    },
    RegionProfile {
        country_code: "TM",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_ASHGABAT,
        timezones: &[TZ_ASIA_ASHGABAT],
        sub_region: None,
        display_name: Some("Turkmenistan"),
    },
    RegionProfile {
        country_code: "TV",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_FUNAFUTI,
        timezones: &[TZ_PACIFIC_FUNAFUTI],
        sub_region: None,
        display_name: Some("Tuvalu"),
    },
    RegionProfile {
        country_code: "UZ",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_TASHKENT,
        timezones: &[TZ_ASIA_TASHKENT],
        sub_region: None,
        display_name: Some("Uzbekistan"),
    },
    RegionProfile {
        country_code: "VU",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_EFATE,
        timezones: &[TZ_PACIFIC_EFATE],
        sub_region: None,
        display_name: Some("Vanuatu"),
    },
    RegionProfile {
        country_code: "VN",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_HANOI,
        timezones: &[TZ_ASIA_HANOI],
        sub_region: None,
        display_name: Some("Vietnam"),
    },
    RegionProfile {
        country_code: "CK",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_RAROTONGA,
        timezones: &[TZ_PACIFIC_RAROTONGA],
        sub_region: Some("New Zealand"),
        display_name: Some("Cook Islands"),
    },
    RegionProfile {
        country_code: "NU",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_NIUE,
        timezones: &[TZ_PACIFIC_NIUE],
        sub_region: Some("New Zealand"),
        display_name: Some("Niue"),
    },
    RegionProfile {
        country_code: "TK",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_FAKAOFO,
        timezones: &[TZ_PACIFIC_FAKAOFO],
        sub_region: Some("New Zealand"),
        display_name: Some("Tokelau"),
    },
    RegionProfile {
        country_code: "HK",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_HONG_KONG,
        timezones: &[TZ_ASIA_HONG_KONG],
        sub_region: Some("China"),
        display_name: Some("Hong Kong"),
    },
];
