use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const AMERICAS_PROFILES_PART_2: &[RegionProfile] = &[
    RegionProfile {
        country_code: "JM",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_JAMAICA,
        timezones: &[TZ_AMERICA_JAMAICA],
        sub_region: None,
        display_name: Some("Jamaica"),
    },
    RegionProfile {
        country_code: "NI",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_MANAGUA,
        timezones: &[TZ_AMERICA_MANAGUA],
        sub_region: None,
        display_name: Some("Nicaragua"),
    },
    RegionProfile {
        country_code: "PA",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_PANAMA,
        timezones: &[TZ_AMERICA_PANAMA],
        sub_region: None,
        display_name: Some("Panama"),
    },
    RegionProfile {
        country_code: "PY",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_ASUNCION,
        timezones: &[TZ_AMERICA_ASUNCION],
        sub_region: None,
        display_name: Some("Paraguay"),
    },
    RegionProfile {
        country_code: "PE",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_LIMA,
        timezones: &[TZ_AMERICA_LIMA],
        sub_region: None,
        display_name: Some("Peru"),
    },
    RegionProfile {
        country_code: "PR",
        data_region: DataRegion::Us,
        legal_jurisdiction: LegalJurisdiction::Ccpa,
        primary_timezone: TZ_AMERICA_PUERTO_RICO,
        timezones: &[TZ_AMERICA_PUERTO_RICO],
        sub_region: Some("United States"),
        display_name: Some("Puerto Rico"),
    },
    RegionProfile {
        country_code: "SR",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_PARAMARIBO,
        timezones: &[TZ_AMERICA_PARAMARIBO],
        sub_region: None,
        display_name: Some("Suriname"),
    },
    RegionProfile {
        country_code: "TT",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_PORT_OF_SPAIN,
        timezones: &[TZ_AMERICA_PORT_OF_SPAIN],
        sub_region: None,
        display_name: Some("Trinidad and Tobago"),
    },
    RegionProfile {
        country_code: "UY",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_MONTEVIDEO,
        timezones: &[TZ_AMERICA_MONTEVIDEO],
        sub_region: None,
        display_name: Some("Uruguay"),
    },
    RegionProfile {
        country_code: "VE",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_CARACAS,
        timezones: &[TZ_AMERICA_CARACAS],
        sub_region: None,
        display_name: Some("Venezuela"),
    },
    RegionProfile {
        country_code: "BZ",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_BELIZE,
        timezones: &[TZ_AMERICA_BELIZE],
        sub_region: None,
        display_name: Some("Belize"),
    },
    RegionProfile {
        country_code: "BS",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_NASSAU,
        timezones: &[TZ_AMERICA_NASSAU],
        sub_region: None,
        display_name: Some("Bahamas"),
    },
    RegionProfile {
        country_code: "BB",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_BARBADOS,
        timezones: &[TZ_AMERICA_BARBADOS],
        sub_region: None,
        display_name: Some("Barbados"),
    },
    RegionProfile {
        country_code: "AG",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_ANTIGUA,
        timezones: &[TZ_AMERICA_ANTIGUA],
        sub_region: None,
        display_name: Some("Antigua and Barbuda"),
    },
    RegionProfile {
        country_code: "DM",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_DOMINICA,
        timezones: &[TZ_AMERICA_DOMINICA],
        sub_region: None,
        display_name: Some("Dominica"),
    },
    RegionProfile {
        country_code: "GD",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_GRENADA,
        timezones: &[TZ_AMERICA_GRENADA],
        sub_region: None,
        display_name: Some("Grenada"),
    },
    RegionProfile {
        country_code: "KN",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_ST_KITTS,
        timezones: &[TZ_AMERICA_ST_KITTS],
        sub_region: None,
        display_name: Some("Saint Kitts and Nevis"),
    },
    RegionProfile {
        country_code: "LC",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_ST_LUCIA,
        timezones: &[TZ_AMERICA_ST_LUCIA],
        sub_region: None,
        display_name: Some("Saint Lucia"),
    },
    RegionProfile {
        country_code: "VC",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AMERICA_ST_VINCENT,
        timezones: &[TZ_AMERICA_ST_VINCENT],
        sub_region: None,
        display_name: Some("Saint Vincent and the Grenadines"),
    },
    RegionProfile {
        country_code: "VI",
        data_region: DataRegion::Us,
        legal_jurisdiction: LegalJurisdiction::Ccpa,
        primary_timezone: TZ_AMERICA_ST_THOMAS,
        timezones: &[TZ_AMERICA_ST_THOMAS],
        sub_region: Some("United States"),
        display_name: Some("U.S. Virgin Islands"),
    },
    RegionProfile {
        country_code: "GU",
        data_region: DataRegion::Us,
        legal_jurisdiction: LegalJurisdiction::Ccpa,
        primary_timezone: TZ_PACIFIC_GUAM,
        timezones: &[TZ_PACIFIC_GUAM],
        sub_region: Some("United States"),
        display_name: Some("Guam"),
    },
    RegionProfile {
        country_code: "MP",
        data_region: DataRegion::Us,
        legal_jurisdiction: LegalJurisdiction::Ccpa,
        primary_timezone: TZ_PACIFIC_SAIPAN,
        timezones: &[TZ_PACIFIC_SAIPAN],
        sub_region: Some("United States"),
        display_name: Some("Northern Mariana Islands"),
    },
    RegionProfile {
        country_code: "AS",
        data_region: DataRegion::Us,
        legal_jurisdiction: LegalJurisdiction::Ccpa,
        primary_timezone: TZ_PACIFIC_PAGO_PAGO,
        timezones: &[TZ_PACIFIC_PAGO_PAGO],
        sub_region: Some("United States"),
        display_name: Some("American Samoa"),
    },
    RegionProfile {
        country_code: "AI",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_ANGUILLA,
        timezones: &[TZ_AMERICA_ANGUILLA],
        sub_region: Some("United Kingdom"),
        display_name: Some("Anguilla"),
    },
    RegionProfile {
        country_code: "BM",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_AMERICA_HAMILTON,
        timezones: &[TZ_AMERICA_HAMILTON],
        sub_region: Some("United Kingdom"),
        display_name: Some("Bermuda"),
    },
];
