use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const ASIA_PACIFIC_PROFILES_PART_1: &[RegionProfile] = &[
    RegionProfile {
        country_code: "AF",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_KABUL,
        timezones: &[TZ_ASIA_KABUL],
        sub_region: None,
        display_name: Some("Afghanistan"),
    },
    RegionProfile {
        country_code: "AU",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::App,
        primary_timezone: TZ_AUSTRALIA_SYDNEY,
        timezones: &[
            TZ_AUSTRALIA_SYDNEY,
            TZ_AUSTRALIA_MELBOURNE,
            TZ_AUSTRALIA_BRISBANE,
            TZ_AUSTRALIA_ADELAIDE,
            TZ_AUSTRALIA_DARWIN,
            TZ_AUSTRALIA_PERTH,
            TZ_AUSTRALIA_HOBART,
            TZ_AUSTRALIA_LORD_HOWE,
            TZ_AUSTRALIA_BROKEN_HILL,
            TZ_AUSTRALIA_EUCLA,
        ],
        sub_region: None,
        display_name: Some("Australia"),
    },
    RegionProfile {
        country_code: "BD",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_DHAKA,
        timezones: &[TZ_ASIA_DHAKA],
        sub_region: None,
        display_name: Some("Bangladesh"),
    },
    RegionProfile {
        country_code: "BT",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_THIMPHU,
        timezones: &[TZ_ASIA_THIMPHU],
        sub_region: None,
        display_name: Some("Bhutan"),
    },
    RegionProfile {
        country_code: "BN",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_BANDAR_SERI_BEGAWAN,
        timezones: &[TZ_ASIA_BANDAR_SERI_BEGAWAN],
        sub_region: None,
        display_name: Some("Brunei"),
    },
    RegionProfile {
        country_code: "KH",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_PHNOM_PENH,
        timezones: &[TZ_ASIA_PHNOM_PENH],
        sub_region: None,
        display_name: Some("Cambodia"),
    },
    RegionProfile {
        country_code: "CN",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Pipl,
        primary_timezone: TZ_ASIA_SHANGHAI,
        timezones: &[TZ_ASIA_SHANGHAI],
        sub_region: None,
        display_name: Some("China"),
    },
    RegionProfile {
        country_code: "FJ",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_FIJI,
        timezones: &[TZ_PACIFIC_FIJI],
        sub_region: None,
        display_name: Some("Fiji"),
    },
    RegionProfile {
        country_code: "IN",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_KOLKATA,
        timezones: &[TZ_ASIA_KOLKATA],
        sub_region: None,
        display_name: Some("India"),
    },
    RegionProfile {
        country_code: "ID",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_JAKARTA,
        timezones: &[
            TZ_ASIA_JAKARTA,
            TZ_ASIA_PONTIANAK,
            TZ_ASIA_MAKASSAR,
            TZ_ASIA_JAYAPURA,
        ],
        sub_region: None,
        display_name: Some("Indonesia"),
    },
    RegionProfile {
        country_code: "JP",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_TOKYO,
        timezones: &[TZ_ASIA_TOKYO],
        sub_region: None,
        display_name: Some("Japan"),
    },
    RegionProfile {
        country_code: "KZ",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_ALMATY,
        timezones: &[
            TZ_ASIA_ALMATY,
            TZ_ASIA_AQTOBE,
            TZ_ASIA_ATYRAU,
            TZ_ASIA_QOSTANAY,
            TZ_ASIA_QYZYLORDA,
            TZ_ASIA_ORAL,
        ],
        sub_region: None,
        display_name: Some("Kazakhstan"),
    },
    RegionProfile {
        country_code: "KI",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_TARAWA,
        timezones: &[TZ_PACIFIC_TARAWA, TZ_PACIFIC_KANTON, TZ_PACIFIC_KIRITIMATI],
        sub_region: None,
        display_name: Some("Kiribati"),
    },
    RegionProfile {
        country_code: "KP",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_PYONGYANG,
        timezones: &[TZ_ASIA_PYONGYANG],
        sub_region: None,
        display_name: Some("North Korea"),
    },
    RegionProfile {
        country_code: "KR",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_SEOUL,
        timezones: &[TZ_ASIA_SEOUL],
        sub_region: None,
        display_name: Some("South Korea"),
    },
    RegionProfile {
        country_code: "KG",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_BISHKEK,
        timezones: &[TZ_ASIA_BISHKEK],
        sub_region: None,
        display_name: Some("Kyrgyzstan"),
    },
    RegionProfile {
        country_code: "LA",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_VIENTIANE,
        timezones: &[TZ_ASIA_VIENTIANE],
        sub_region: None,
        display_name: Some("Laos"),
    },
    RegionProfile {
        country_code: "MY",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Pdpa,
        primary_timezone: TZ_ASIA_KUALA_LUMPUR,
        timezones: &[TZ_ASIA_KUALA_LUMPUR],
        sub_region: None,
        display_name: Some("Malaysia"),
    },
    RegionProfile {
        country_code: "MV",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_INDIAN_MALDIVES,
        timezones: &[TZ_INDIAN_MALDIVES],
        sub_region: None,
        display_name: Some("Maldives"),
    },
    RegionProfile {
        country_code: "MH",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_MAJURO,
        timezones: &[TZ_PACIFIC_MAJURO, TZ_PACIFIC_KWAJALEIN],
        sub_region: None,
        display_name: Some("Marshall Islands"),
    },
    RegionProfile {
        country_code: "FM",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_PACIFIC_POHNPEI,
        timezones: &[TZ_PACIFIC_POHNPEI, TZ_PACIFIC_KOSRAE, TZ_PACIFIC_CHUUK],
        sub_region: None,
        display_name: Some("Micronesia"),
    },
    RegionProfile {
        country_code: "MN",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_ULAANBAATAR,
        timezones: &[TZ_ASIA_ULAANBAATAR, TZ_ASIA_HOVD, TZ_ASIA_CHOIBALSAN],
        sub_region: None,
        display_name: Some("Mongolia"),
    },
    RegionProfile {
        country_code: "MM",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_YANGON,
        timezones: &[TZ_ASIA_YANGON],
        sub_region: None,
        display_name: Some("Myanmar"),
    },
];
