use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const AFRICA_ME_PROFILES_PART_3: &[RegionProfile] = &[
    RegionProfile {
        country_code: "TN",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Inpdp,
        primary_timezone: TZ_AFRICA_TUNIS,
        timezones: &[TZ_AFRICA_TUNIS],
        sub_region: None,
        display_name: Some("Tunisia"),
    },
    RegionProfile {
        country_code: "UG",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_KAMPALA,
        timezones: &[TZ_AFRICA_KAMPALA],
        sub_region: None,
        display_name: Some("Uganda"),
    },
    RegionProfile {
        country_code: "EH",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_EL_AAIUN,
        timezones: &[TZ_AFRICA_EL_AAIUN],
        sub_region: None,
        display_name: Some("Western Sahara"),
    },
    RegionProfile {
        country_code: "ZM",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_LUSAKA,
        timezones: &[TZ_AFRICA_LUSAKA],
        sub_region: None,
        display_name: Some("Zambia"),
    },
    RegionProfile {
        country_code: "ZW",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_HARARE,
        timezones: &[TZ_AFRICA_HARARE],
        sub_region: None,
        display_name: Some("Zimbabwe"),
    },
    RegionProfile {
        country_code: "SH",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_ATLANTIC_ST_HELENA,
        timezones: &[TZ_ATLANTIC_ST_HELENA],
        sub_region: Some("United Kingdom"),
        display_name: Some("Saint Helena"),
    },
    RegionProfile {
        country_code: "BH",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_RIYADH,
        timezones: &[TZ_ASIA_RIYADH],
        sub_region: None,
        display_name: Some("Bahrain"),
    },
    RegionProfile {
        country_code: "IR",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_TEHRAN,
        timezones: &[TZ_ASIA_TEHRAN],
        sub_region: None,
        display_name: Some("Iran"),
    },
    RegionProfile {
        country_code: "IQ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_BAGHDAD,
        timezones: &[TZ_ASIA_BAGHDAD],
        sub_region: None,
        display_name: Some("Iraq"),
    },
    RegionProfile {
        country_code: "IL",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_JERUSALEM,
        timezones: &[TZ_ASIA_JERUSALEM],
        sub_region: None,
        display_name: Some("Israel"),
    },
    RegionProfile {
        country_code: "JO",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_AMMAN,
        timezones: &[TZ_ASIA_AMMAN],
        sub_region: None,
        display_name: Some("Jordan"),
    },
    RegionProfile {
        country_code: "KW",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_KUWAIT,
        timezones: &[TZ_ASIA_KUWAIT],
        sub_region: None,
        display_name: Some("Kuwait"),
    },
    RegionProfile {
        country_code: "LB",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_BEIRUT,
        timezones: &[TZ_ASIA_BEIRUT],
        sub_region: None,
        display_name: Some("Lebanon"),
    },
    RegionProfile {
        country_code: "OM",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_MUSCAT,
        timezones: &[TZ_ASIA_MUSCAT],
        sub_region: None,
        display_name: Some("Oman"),
    },
    RegionProfile {
        country_code: "PS",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_JERUSALEM,
        timezones: &[TZ_ASIA_JERUSALEM],
        sub_region: None,
        display_name: Some("Palestine"),
    },
    RegionProfile {
        country_code: "QA",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_DOHA,
        timezones: &[TZ_ASIA_DOHA],
        sub_region: None,
        display_name: Some("Qatar"),
    },
    RegionProfile {
        country_code: "SA",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_RIYADH,
        timezones: &[TZ_ASIA_RIYADH],
        sub_region: None,
        display_name: Some("Saudi Arabia"),
    },
    RegionProfile {
        country_code: "SY",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_DAMASCUS,
        timezones: &[TZ_ASIA_DAMASCUS],
        sub_region: None,
        display_name: Some("Syria"),
    },
    RegionProfile {
        country_code: "AE",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_DUBAI,
        timezones: &[TZ_ASIA_DUBAI],
        sub_region: None,
        display_name: Some("United Arab Emirates"),
    },
    RegionProfile {
        country_code: "YE",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_ADEN,
        timezones: &[TZ_ASIA_ADEN],
        sub_region: None,
        display_name: Some("Yemen"),
    },
    RegionProfile {
        country_code: "GS",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_ATLANTIC_SOUTH_GEORGIA,
        timezones: &[TZ_ATLANTIC_SOUTH_GEORGIA],
        sub_region: Some("United Kingdom"),
        display_name: Some("South Georgia"),
    },
    RegionProfile {
        country_code: "IO",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_INDIAN_CHAGOS,
        timezones: &[TZ_INDIAN_CHAGOS],
        sub_region: Some("United Kingdom"),
        display_name: Some("British Indian Ocean Territory"),
    },
];
