use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const EUROPE_PROFILES_PART_2: &[RegionProfile] = &[
    RegionProfile {
        country_code: "ES",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_MADRID,
        timezones: &[TZ_EUROPE_MADRID, TZ_ATLANTIC_CANARY],
        sub_region: None,
        display_name: Some("Spain"),
    },
    RegionProfile {
        country_code: "SE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_STOCKHOLM,
        timezones: &[TZ_EUROPE_STOCKHOLM],
        sub_region: None,
        display_name: Some("Sweden"),
    },
    RegionProfile {
        country_code: "IS",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_ATLANTIC_REYKJAVIK,
        timezones: &[TZ_ATLANTIC_REYKJAVIK],
        sub_region: None,
        display_name: Some("Iceland"),
    },
    RegionProfile {
        country_code: "LI",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_ZURICH,
        timezones: &[TZ_EUROPE_ZURICH],
        sub_region: None,
        display_name: Some("Liechtenstein"),
    },
    RegionProfile {
        country_code: "NO",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_OSLO,
        timezones: &[TZ_EUROPE_OSLO],
        sub_region: None,
        display_name: Some("Norway"),
    },
    RegionProfile {
        country_code: "CH",
        data_region: DataRegion::Ch,
        legal_jurisdiction: LegalJurisdiction::Nfdap,
        primary_timezone: TZ_EUROPE_ZURICH,
        timezones: &[TZ_EUROPE_ZURICH],
        sub_region: None,
        display_name: Some("Switzerland"),
    },
    RegionProfile {
        country_code: "GB",
        data_region: DataRegion::Uk,
        legal_jurisdiction: LegalJurisdiction::UkGdpr,
        primary_timezone: TZ_EUROPE_LONDON,
        timezones: &[TZ_EUROPE_LONDON],
        sub_region: None,
        display_name: Some("United Kingdom"),
    },
    RegionProfile {
        country_code: "AL",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_TIRANA,
        timezones: &[TZ_EUROPE_TIRANA],
        sub_region: None,
        display_name: Some("Albania"),
    },
    RegionProfile {
        country_code: "AD",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_ANDORRA,
        timezones: &[TZ_EUROPE_ANDORRA],
        sub_region: None,
        display_name: Some("Andorra"),
    },
    RegionProfile {
        country_code: "AM",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_YEREVAN,
        timezones: &[TZ_ASIA_YEREVAN],
        sub_region: None,
        display_name: Some("Armenia"),
    },
    RegionProfile {
        country_code: "AZ",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_BAKU,
        timezones: &[TZ_ASIA_BAKU],
        sub_region: None,
        display_name: Some("Azerbaijan"),
    },
    RegionProfile {
        country_code: "BY",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_EUROPE_MINSK,
        timezones: &[TZ_EUROPE_MINSK],
        sub_region: None,
        display_name: Some("Belarus"),
    },
    RegionProfile {
        country_code: "BA",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_SARAJEVO,
        timezones: &[TZ_EUROPE_SARAJEVO],
        sub_region: None,
        display_name: Some("Bosnia and Herzegovina"),
    },
    RegionProfile {
        country_code: "GE",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_TBILISI,
        timezones: &[TZ_ASIA_TBILISI],
        sub_region: None,
        display_name: Some("Georgia"),
    },
    RegionProfile {
        country_code: "GI",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_GIBRALTAR,
        timezones: &[TZ_EUROPE_GIBRALTAR],
        sub_region: None,
        display_name: Some("Gibraltar"),
    },
    RegionProfile {
        country_code: "GG",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_LONDON,
        timezones: &[TZ_EUROPE_LONDON],
        sub_region: Some("Crown Dependency"),
        display_name: Some("Guernsey"),
    },
    RegionProfile {
        country_code: "VA",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_VATICAN,
        timezones: &[TZ_EUROPE_VATICAN],
        sub_region: None,
        display_name: Some("Vatican City"),
    },
    RegionProfile {
        country_code: "IM",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_LONDON,
        timezones: &[TZ_EUROPE_LONDON],
        sub_region: Some("Crown Dependency"),
        display_name: Some("Isle of Man"),
    },
    RegionProfile {
        country_code: "JE",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_LONDON,
        timezones: &[TZ_EUROPE_LONDON],
        sub_region: Some("Crown Dependency"),
        display_name: Some("Jersey"),
    },
    RegionProfile {
        country_code: "MC",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_MONACO,
        timezones: &[TZ_EUROPE_MONACO],
        sub_region: None,
        display_name: Some("Monaco"),
    },
    RegionProfile {
        country_code: "ME",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_PODGORICA,
        timezones: &[TZ_EUROPE_PODGORICA],
        sub_region: None,
        display_name: Some("Montenegro"),
    },
    RegionProfile {
        country_code: "MK",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_SKOPJE,
        timezones: &[TZ_EUROPE_SKOPJE],
        sub_region: None,
        display_name: Some("North Macedonia"),
    },
    RegionProfile {
        country_code: "MD",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_CHISINAU,
        timezones: &[TZ_EUROPE_CHISINAU],
        sub_region: None,
        display_name: Some("Moldova"),
    },
    RegionProfile {
        country_code: "RS",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_BELGRADE,
        timezones: &[TZ_EUROPE_BELGRADE],
        sub_region: None,
        display_name: Some("Serbia"),
    },
    RegionProfile {
        country_code: "SM",
        data_region: DataRegion::Eu,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_EUROPE_SAN_MARINO,
        timezones: &[TZ_EUROPE_SAN_MARINO],
        sub_region: None,
        display_name: Some("San Marino"),
    },
];
