use crate::timezones::*;
use crate::{DataRegion, LegalJurisdiction, RegionProfile};

pub const AFRICA_ME_PROFILES: &[RegionProfile] = &[
    RegionProfile {
        country_code: "DZ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_ALGIERS,
        timezones: &[TZ_AFRICA_ALGIERS],
        sub_region: None,
        display_name: Some("Algeria"),
    },
    RegionProfile {
        country_code: "AO",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_LUANDA,
        timezones: &[TZ_AFRICA_LUANDA],
        sub_region: None,
        display_name: Some("Angola"),
    },
    RegionProfile {
        country_code: "BJ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_PORTO_NOVO,
        timezones: &[TZ_AFRICA_PORTO_NOVO],
        sub_region: None,
        display_name: Some("Benin"),
    },
    RegionProfile {
        country_code: "BW",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_GABORONE,
        timezones: &[TZ_AFRICA_GABORONE],
        sub_region: None,
        display_name: Some("Botswana"),
    },
    RegionProfile {
        country_code: "BF",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_OUAGADOUGOU,
        timezones: &[TZ_AFRICA_OUAGADOUGOU],
        sub_region: None,
        display_name: Some("Burkina Faso"),
    },
    RegionProfile {
        country_code: "BI",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_BUJUMBURA,
        timezones: &[TZ_AFRICA_BUJUMBURA],
        sub_region: None,
        display_name: Some("Burundi"),
    },
    RegionProfile {
        country_code: "CV",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ATLANTIC_CAPE_VERDE,
        timezones: &[TZ_ATLANTIC_CAPE_VERDE],
        sub_region: None,
        display_name: Some("Cabo Verde"),
    },
    RegionProfile {
        country_code: "CM",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_YAOUNDE,
        timezones: &[TZ_AFRICA_YAOUNDE],
        sub_region: None,
        display_name: Some("Cameroon"),
    },
    RegionProfile {
        country_code: "CF",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_BANGUI,
        timezones: &[TZ_AFRICA_BANGUI],
        sub_region: None,
        display_name: Some("Central African Republic"),
    },
    RegionProfile {
        country_code: "TD",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_NDJAMENA,
        timezones: &[TZ_AFRICA_NDJAMENA],
        sub_region: None,
        display_name: Some("Chad"),
    },
    RegionProfile {
        country_code: "KM",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_COMORO,
        timezones: &[TZ_AFRICA_COMORO],
        sub_region: None,
        display_name: Some("Comoros"),
    },
    RegionProfile {
        country_code: "CG",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_BRAZZAVILLE,
        timezones: &[TZ_AFRICA_BRAZZAVILLE],
        sub_region: None,
        display_name: Some("Congo"),
    },
    RegionProfile {
        country_code: "CD",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_KINSHASA,
        timezones: &[TZ_AFRICA_KINSHASA, TZ_AFRICA_LUBUMBASHI],
        sub_region: None,
        display_name: Some("Democratic Republic of the Congo"),
    },
    RegionProfile {
        country_code: "CI",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_ABIDJAN,
        timezones: &[TZ_AFRICA_ABIDJAN],
        sub_region: None,
        display_name: Some("Cote d'Ivoire"),
    },
    RegionProfile {
        country_code: "DJ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_ADDIS_ABABA,
        timezones: &[TZ_AFRICA_ADDIS_ABABA],
        sub_region: None,
        display_name: Some("Djibouti"),
    },
    RegionProfile {
        country_code: "EG",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_CAIRO,
        timezones: &[TZ_AFRICA_CAIRO],
        sub_region: None,
        display_name: Some("Egypt"),
    },
    RegionProfile {
        country_code: "GQ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MALABO,
        timezones: &[TZ_AFRICA_MALABO],
        sub_region: None,
        display_name: Some("Equatorial Guinea"),
    },
    RegionProfile {
        country_code: "ER",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_ASMARA,
        timezones: &[TZ_AFRICA_ASMARA],
        sub_region: None,
        display_name: Some("Eritrea"),
    },
    RegionProfile {
        country_code: "SZ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MBABANE,
        timezones: &[TZ_AFRICA_MBABANE],
        sub_region: None,
        display_name: Some("Eswatini"),
    },
    RegionProfile {
        country_code: "ET",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_ADDIS_ABABA,
        timezones: &[TZ_AFRICA_ADDIS_ABABA],
        sub_region: None,
        display_name: Some("Ethiopia"),
    },
    RegionProfile {
        country_code: "GA",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_LIBREVILLE,
        timezones: &[TZ_AFRICA_LIBREVILLE],
        sub_region: None,
        display_name: Some("Gabon"),
    },
    RegionProfile {
        country_code: "GM",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_BANJUL,
        timezones: &[TZ_AFRICA_BANJUL],
        sub_region: None,
        display_name: Some("Gambia"),
    },
    RegionProfile {
        country_code: "GH",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_ACCRA,
        timezones: &[TZ_AFRICA_ACCRA],
        sub_region: None,
        display_name: Some("Ghana"),
    },
    RegionProfile {
        country_code: "GN",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_CONAKRY,
        timezones: &[TZ_AFRICA_CONAKRY],
        sub_region: None,
        display_name: Some("Guinea"),
    },
    RegionProfile {
        country_code: "GW",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_BISSAU,
        timezones: &[TZ_AFRICA_BISSAU],
        sub_region: None,
        display_name: Some("Guinea-Bissau"),
    },
    RegionProfile {
        country_code: "KE",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_NAIROBI,
        timezones: &[TZ_AFRICA_NAIROBI],
        sub_region: None,
        display_name: Some("Kenya"),
    },
    RegionProfile {
        country_code: "LS",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MASERU,
        timezones: &[TZ_AFRICA_MASERU],
        sub_region: None,
        display_name: Some("Lesotho"),
    },
    RegionProfile {
        country_code: "LR",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MONROVIA,
        timezones: &[TZ_AFRICA_MONROVIA],
        sub_region: None,
        display_name: Some("Liberia"),
    },
    RegionProfile {
        country_code: "LY",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_TRIPOLI,
        timezones: &[TZ_AFRICA_TRIPOLI],
        sub_region: None,
        display_name: Some("Libya"),
    },
    RegionProfile {
        country_code: "MG",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_ANTANANARIVO,
        timezones: &[TZ_AFRICA_ANTANANARIVO],
        sub_region: None,
        display_name: Some("Madagascar"),
    },
    RegionProfile {
        country_code: "MW",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_LILONGWE,
        timezones: &[TZ_AFRICA_LILONGWE],
        sub_region: None,
        display_name: Some("Malawi"),
    },
    RegionProfile {
        country_code: "ML",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_BAMAKO,
        timezones: &[TZ_AFRICA_BAMAKO],
        sub_region: None,
        display_name: Some("Mali"),
    },
    RegionProfile {
        country_code: "MR",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_NOUAKCHOTT,
        timezones: &[TZ_AFRICA_NOUAKCHOTT],
        sub_region: None,
        display_name: Some("Mauritania"),
    },
    RegionProfile {
        country_code: "MU",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MAURITIUS,
        timezones: &[TZ_AFRICA_MAURITIUS],
        sub_region: None,
        display_name: Some("Mauritius"),
    },
    RegionProfile {
        country_code: "MA",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_CASABLANCA,
        timezones: &[TZ_AFRICA_CASABLANCA],
        sub_region: None,
        display_name: Some("Morocco"),
    },
    RegionProfile {
        country_code: "MZ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MAPUTO,
        timezones: &[TZ_AFRICA_MAPUTO],
        sub_region: None,
        display_name: Some("Mozambique"),
    },
    RegionProfile {
        country_code: "NA",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_WINDHOEK,
        timezones: &[TZ_AFRICA_WINDHOEK],
        sub_region: None,
        display_name: Some("Namibia"),
    },
    RegionProfile {
        country_code: "NE",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_NIAMEY,
        timezones: &[TZ_AFRICA_NIAMEY],
        sub_region: None,
        display_name: Some("Niger"),
    },
    RegionProfile {
        country_code: "NG",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_LAGOS,
        timezones: &[TZ_AFRICA_LAGOS],
        sub_region: None,
        display_name: Some("Nigeria"),
    },
    RegionProfile {
        country_code: "RW",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_KIGALI,
        timezones: &[TZ_AFRICA_KIGALI],
        sub_region: None,
        display_name: Some("Rwanda"),
    },
    RegionProfile {
        country_code: "ST",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_SAO_TOME,
        timezones: &[TZ_AFRICA_SAO_TOME],
        sub_region: None,
        display_name: Some("Sao Tome and Principe"),
    },
    RegionProfile {
        country_code: "SN",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_DAKAR,
        timezones: &[TZ_AFRICA_DAKAR],
        sub_region: None,
        display_name: Some("Senegal"),
    },
    RegionProfile {
        country_code: "SC",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_SEYCHELLES,
        timezones: &[TZ_AFRICA_SEYCHELLES],
        sub_region: None,
        display_name: Some("Seychelles"),
    },
    RegionProfile {
        country_code: "SL",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_FREETOWN,
        timezones: &[TZ_AFRICA_FREETOWN],
        sub_region: None,
        display_name: Some("Sierra Leone"),
    },
    RegionProfile {
        country_code: "SO",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_MOGADISHU,
        timezones: &[TZ_AFRICA_MOGADISHU],
        sub_region: None,
        display_name: Some("Somalia"),
    },
    RegionProfile {
        country_code: "ZA",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Popia,
        primary_timezone: TZ_AFRICA_JOHANNESBURG,
        timezones: &[TZ_AFRICA_JOHANNESBURG],
        sub_region: None,
        display_name: Some("South Africa"),
    },
    RegionProfile {
        country_code: "SS",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_JUBA,
        timezones: &[TZ_AFRICA_JUBA],
        sub_region: None,
        display_name: Some("South Sudan"),
    },
    RegionProfile {
        country_code: "SD",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_KHARTOUM,
        timezones: &[TZ_AFRICA_KHARTOUM],
        sub_region: None,
        display_name: Some("Sudan"),
    },
    RegionProfile {
        country_code: "TZ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_DAR_ES_SALAAM,
        timezones: &[TZ_AFRICA_DAR_ES_SALAAM],
        sub_region: None,
        display_name: Some("Tanzania"),
    },
    RegionProfile {
        country_code: "TG",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_LOME,
        timezones: &[TZ_AFRICA_LOME],
        sub_region: None,
        display_name: Some("Togo"),
    },
    RegionProfile {
        country_code: "TN",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_TUNIS,
        timezones: &[TZ_AFRICA_TUNIS],
        sub_region: None,
        display_name: Some("Tunisia"),
    },
    RegionProfile {
        country_code: "UG",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_KAMPALA,
        timezones: &[TZ_AFRICA_KAMPALA],
        sub_region: None,
        display_name: Some("Uganda"),
    },
    RegionProfile {
        country_code: "EH",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_EL_AAIUN,
        timezones: &[TZ_AFRICA_EL_AAIUN],
        sub_region: None,
        display_name: Some("Western Sahara"),
    },
    RegionProfile {
        country_code: "ZM",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_LUSAKA,
        timezones: &[TZ_AFRICA_LUSAKA],
        sub_region: None,
        display_name: Some("Zambia"),
    },
    RegionProfile {
        country_code: "ZW",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_AFRICA_HARARE,
        timezones: &[TZ_AFRICA_HARARE],
        sub_region: None,
        display_name: Some("Zimbabwe"),
    },
    RegionProfile {
        country_code: "SH",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_ATLANTIC_ST_HELENA,
        timezones: &[TZ_ATLANTIC_ST_HELENA],
        sub_region: Some("United Kingdom"),
        display_name: Some("Saint Helena"),
    },
    RegionProfile {
        country_code: "BH",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_RIYADH,
        timezones: &[TZ_ASIA_RIYADH],
        sub_region: None,
        display_name: Some("Bahrain"),
    },
    RegionProfile {
        country_code: "IR",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_TEHRAN,
        timezones: &[TZ_ASIA_TEHRAN],
        sub_region: None,
        display_name: Some("Iran"),
    },
    RegionProfile {
        country_code: "IQ",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_BAGHDAD,
        timezones: &[TZ_ASIA_BAGHDAD],
        sub_region: None,
        display_name: Some("Iraq"),
    },
    RegionProfile {
        country_code: "IL",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_JERUSALEM,
        timezones: &[TZ_ASIA_JERUSALEM],
        sub_region: None,
        display_name: Some("Israel"),
    },
    RegionProfile {
        country_code: "JO",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_AMMAN,
        timezones: &[TZ_ASIA_AMMAN],
        sub_region: None,
        display_name: Some("Jordan"),
    },
    RegionProfile {
        country_code: "KW",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_KUWAIT,
        timezones: &[TZ_ASIA_KUWAIT],
        sub_region: None,
        display_name: Some("Kuwait"),
    },
    RegionProfile {
        country_code: "LB",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_BEIRUT,
        timezones: &[TZ_ASIA_BEIRUT],
        sub_region: None,
        display_name: Some("Lebanon"),
    },
    RegionProfile {
        country_code: "OM",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_MUSCAT,
        timezones: &[TZ_ASIA_MUSCAT],
        sub_region: None,
        display_name: Some("Oman"),
    },
    RegionProfile {
        country_code: "PS",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_JERUSALEM,
        timezones: &[TZ_ASIA_JERUSALEM],
        sub_region: None,
        display_name: Some("Palestine"),
    },
    RegionProfile {
        country_code: "QA",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_DOHA,
        timezones: &[TZ_ASIA_DOHA],
        sub_region: None,
        display_name: Some("Qatar"),
    },
    RegionProfile {
        country_code: "SA",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_RIYADH,
        timezones: &[TZ_ASIA_RIYADH],
        sub_region: None,
        display_name: Some("Saudi Arabia"),
    },
    RegionProfile {
        country_code: "SY",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_DAMASCUS,
        timezones: &[TZ_ASIA_DAMASCUS],
        sub_region: None,
        display_name: Some("Syria"),
    },
    RegionProfile {
        country_code: "AE",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_DUBAI,
        timezones: &[TZ_ASIA_DUBAI],
        sub_region: None,
        display_name: Some("United Arab Emirates"),
    },
    RegionProfile {
        country_code: "YE",
        data_region: DataRegion::MeAfrica,
        legal_jurisdiction: LegalJurisdiction::Global,
        primary_timezone: TZ_ASIA_ADEN,
        timezones: &[TZ_ASIA_ADEN],
        sub_region: None,
        display_name: Some("Yemen"),
    },
    RegionProfile {
        country_code: "GS",
        data_region: DataRegion::Latam,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_ATLANTIC_SOUTH_GEORGIA,
        timezones: &[TZ_ATLANTIC_SOUTH_GEORGIA],
        sub_region: Some("United Kingdom"),
        display_name: Some("South Georgia"),
    },
    RegionProfile {
        country_code: "IO",
        data_region: DataRegion::Apac,
        legal_jurisdiction: LegalJurisdiction::Gdpr,
        primary_timezone: TZ_INDIAN_CHAGOS,
        timezones: &[TZ_INDIAN_CHAGOS],
        sub_region: Some("United Kingdom"),
        display_name: Some("British Indian Ocean Territory"),
    },
];
