apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Mimir
    uid: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    editable: true

  - name: Tempo
    uid: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'Mimir'
      nodeGraph:
        enabled: true
      search:
        hide: false
      tracesToLogsV2:
        datasourceUid: 'Loki'
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        tags: [ { key: 'job' }, { key: 'service.name', value: 'service' } ]
        filterByTraceID: true
        filterBySpanID: false
      tracesToProfiles:
        datasourceUid: 'Pyroscope'
        tags: [ { key: 'service.name', value: 'service_name' } ]
        profileTypeId: 'process_cpu:cpu:nanoseconds:cpu:nanoseconds'
      tracesToMetrics:
        datasourceUid: 'Mimir'
        spanAttributes: [ 'service.name', 'http.method', 'http.status_code' ]
        tags: [ 'job', 'instance' ]
        queries:
          - name: 'Sample Query'
            query: 'sum(rate(http_request_duration_seconds_count{$$__tags}[5m]))'

  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Pyroscope
    uid: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    editable: true
