global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    environment: development
    platform: nvbes

remote_write:
  - url: http://mimir:9009/api/v1/push
    send_exemplars: true

scrape_configs:
  - job_name: 'account-service'
    static_configs:
      - targets: ['host.docker.internal:4000']
        labels:
          service: 'account-service'
          environment: 'development'

  - job_name: 'account-worker'
    static_configs:
      - targets: ['host.docker.internal:4102']
        labels:
          service: 'account-worker'
          environment: 'development'

  - job_name: 'email-worker'
    static_configs:
      - targets: ['host.docker.internal:3040']
        labels:
          service: 'email-worker'
          environment: 'development'

  - job_name: 'grafana-stack'
    static_configs:
      - targets:
          - 'alloy:12345'
          - 'prometheus:9090'
          - 'mimir:9009'
          - 'tempo:3200'
          - 'loki:3100'
          - 'pyroscope:4040'
