[package]
name = "nvbes-product-account"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
chrono.workspace = true
nvbes-core = { path = "../../core" }
nvbes-redis = { path = "../../redis" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true
