//! # Bot Guard
//!
//! Lightweight, zero-dependency anti-automation layer implementing three
//! complementary mechanisms that work without any external service.
//!
//! ## Mechanisms
//! 1. **Honeypot** — Hidden form field that only bots fill out.
//! 2. **Time-lock** — Minimum time between form render and submission.
//! 3. **JS Dynamic Signature** — HMAC-SHA256 proof that the client ran JavaScript.
//!
//! These are designed to complement (not replace) Turnstile, catching cheap
//! scrapers and curl-based bots that skip the Turnstile widget entirely.

use crate::http::error::AppError;
use hmac::{Hmac, Mac};
use sha2::Sha256;

type HmacSha256 = Hmac<Sha256>;

/// Namespace prefix used when deriving the bot-guard HMAC key from `jwt_secret`.
/// This ensures bot-guard tokens cannot be confused with JWTs or other signed values.
const BOT_GUARD_KEY_PREFIX: &str = "bg_v1:";

/// Minimum time (ms) a legitimate user is expected to take filling out the form.
/// Submissions arriving faster than this are flagged as automated.
const MIN_FORM_DURATION_MS: i64 = 1_500;

/// Maximum age (ms) of a form timestamp before we reject it as stale.
/// Prevents attackers from pre-generating proofs and caching them.
const MAX_FORM_AGE_MS: i64 = 10 * 60 * 1_000; // 10 minutes

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Client-side metadata attached to form submissions for enhanced
/// session integrity verification.
#[derive(Debug, serde::Deserialize, utoipa::ToSchema)]
pub struct BotGuardProof {
    /// Optional referral or profile URL associated with the submission.
    pub website: Option<String>,

    /// Client-side session initialization timestamp (Unix ms).
    pub form_ts: Option<i64>,

    /// Client integrity signature.
    pub js_sig: Option<String>,
}

/// Verifies all three bot-guard checks for a given action.
pub fn verify(proof: &BotGuardProof, action: &str, jwt_secret: &str) -> Result<(), AppError> {
    check_decoy_field(proof)?;

    let now_ms = chrono::Utc::now().timestamp_millis();

    if let Some(form_ts) = proof.form_ts {
        check_time_lock(form_ts, now_ms)?;

        if let Some(sig) = &proof.js_sig {
            check_js_signature(sig, form_ts, action, jwt_secret)?;
        }
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Individual checks (pub for unit-testing)
// ---------------------------------------------------------------------------

// Checks whether the decoy field contains any automated content.
// Named generically to avoid revealing its purpose in stack traces / logs.
pub(crate) fn check_decoy_field(proof: &BotGuardProof) -> Result<(), AppError> {
    let val = match &proof.website {
        Some(v) => v.trim().to_lowercase(),
        None => return Ok(()),
    };

    if val.is_empty() {
        return Ok(());
    }

    // Any non-empty value is suspicious, but we also detect common bot
    // auto-fill patterns to log richer telemetry for future tuning.
    let pattern =
        if val.starts_with("http://") || val.starts_with("https://") || val.contains("www.") {
            "url"
        } else if val.contains('@') && val.contains('.') {
            "email"
        } else if val.chars().filter(|c| c.is_ascii_digit()).count() > 6 {
            "phone"
        } else {
            "text"
        };

    tracing::warn!(
        fill_pattern = pattern,
        "Integrity check failed on optional profile field"
    );

    Err(AppError::forbidden(
        "bot_honeypot_triggered",
        "Automated submission detected.",
    ))
}

/// **Time-lock check** — rejects submissions that arrive suspiciously fast.
///
/// `form_ts` is a Unix timestamp in **milliseconds** generated by JavaScript
/// at the moment the form was first rendered. The server checks:
/// - The submission is at least [`MIN_FORM_DURATION_MS`] after render.
/// - The form is not older than [`MAX_FORM_AGE_MS`] (prevents pre-generation).
pub fn check_time_lock(form_ts: i64, now_ms: i64) -> Result<(), AppError> {
    let elapsed = now_ms - form_ts;

    if elapsed < 0 {
        tracing::warn!(form_ts, now_ms, "Bot guard: form_ts is in the future");
        return Err(AppError::forbidden(
            "bot_time_lock_future",
            "Form timestamp is invalid.",
        ));
    }

    if elapsed < MIN_FORM_DURATION_MS {
        tracing::warn!(
            elapsed_ms = elapsed,
            min_ms = MIN_FORM_DURATION_MS,
            "Bot guard: submission too fast"
        );
        return Err(AppError::forbidden(
            "bot_time_lock_fast",
            "Form was submitted too quickly.",
        ));
    }

    if elapsed > MAX_FORM_AGE_MS {
        tracing::warn!(
            elapsed_ms = elapsed,
            max_ms = MAX_FORM_AGE_MS,
            "Bot guard: form_ts is stale"
        );
        return Err(AppError::forbidden(
            "bot_time_lock_expired",
            "Form session has expired. Please refresh and try again.",
        ));
    }

    Ok(())
}

/// **JS dynamic signature check** — verifies that client-side JavaScript ran.
///
/// The client must compute `HMAC-SHA256(key, "{form_ts}:{action}")` where
/// `key = SHA256(BOT_GUARD_KEY_PREFIX + jwt_secret)`. The expected algorithm
/// for the front-end is documented in `identity-sdk-web`.
///
/// This rejects:
/// - Raw `curl` / `httpie` clients (no JS runtime).
/// - Simple HTTP bots in Node.js or Python that skip the signing step.
/// - Replay attacks (the signature is bound to both `form_ts` and `action`).
pub fn check_js_signature(
    provided_sig: &str,
    form_ts: i64,
    action: &str,
    jwt_secret: &str,
) -> Result<(), AppError> {
    let key = derive_key(jwt_secret);
    let message = format!("{form_ts}:{action}");
    let expected = compute_hmac(&key, &message);

    // Constant-time comparison to prevent timing side-channels
    if !constant_time_eq(provided_sig, &expected) {
        tracing::warn!(
            action,
            "Bot guard: JS signature mismatch — possible non-browser client"
        );
        return Err(AppError::forbidden(
            "bot_js_signature_invalid",
            "Security challenge signature is invalid.",
        ));
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Derives a stable HMAC key from `jwt_secret` with a domain-specific prefix.
fn derive_key(jwt_secret: &str) -> Vec<u8> {
    use sha2::Digest;
    let mut hasher = sha2::Sha256::new();
    hasher.update(BOT_GUARD_KEY_PREFIX.as_bytes());
    hasher.update(jwt_secret.as_bytes());
    hasher.finalize().to_vec()
}

/// Computes HMAC-SHA256 and returns a lowercase hex string.
fn compute_hmac(key: &[u8], message: &str) -> String {
    let mut mac = HmacSha256::new_from_slice(key).expect("HMAC accepts keys of any length");
    mac.update(message.as_bytes());
    hex::encode(mac.finalize().into_bytes())
}

/// Constant-time string comparison to prevent timing attacks.
fn constant_time_eq(a: &str, b: &str) -> bool {
    let a = a.as_bytes();
    let b = b.as_bytes();
    if a.len() != b.len() {
        return false;
    }
    a.iter()
        .zip(b.iter())
        .fold(0u8, |acc, (x, y)| acc | (x ^ y))
        == 0
}

#[cfg(test)]
#[path = "identity.domains.auth.bot_guard.tests.rs"]
mod tests;
