use utoipa::OpenApi;
use utoipa_swagger_ui::SwaggerUi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "nvbes Identity API",
        version = "0.1.0",
        description = "Authentication, authorization, and identity management API",
        contact(name = "nvbes", url = "https://nvbes.fr"),
        license(name = "UNLICENSED"),
    ),
    servers(
        (url = "https://identity.nvbes.fr", description = "Production"),
        (url = "http://localhost:8080", description = "Development"),
    ),
    tags(
        (name = "auth", description = "Authentication & sessions"),
        (name = "mfa", description = "Multi-factor authentication"),
        (name = "oauth", description = "OAuth2 authorization server"),
        (name = "service-accounts", description = "Workspace service account management"),
        (name = "workspaces", description = "Workspace management"),
        (name = "members", description = "Workspace members & invitations"),
        (name = "federation", description = "Federated identity providers"),
        (name = "billing", description = "Billing & subscriptions"),
        (name = "security", description = "Security events & audit"),
        (name = "authz", description = "Authorization decisions"),
        (name = "developer", description = "Developer portal, apps, webhooks, logs, and integration tools"),
    ),
    paths(
        crate::domains::auth::routes::register::register,
        crate::domains::auth::routes::register::region,
        crate::domains::auth::routes::register::supported_regions,
        crate::domains::auth::routes::register::verify_email,
        crate::domains::auth::routes::login::identifier::challenge_identifier,
        crate::domains::auth::routes::login::mfa::challenge_mfa,
        crate::domains::auth::routes::login::pwd::challenge_pwd,
        crate::domains::auth::routes::login::webauthn::challenge_webauthn_start,
        crate::domains::auth::routes::verification::change_verify_email,
        crate::domains::auth::routes::verification::resend_verify_email,
        crate::domains::auth::routes::session_mgmt::get_accounts,
        crate::domains::auth::routes::session_mgmt::list_sessions,
        crate::domains::auth::routes::session_mgmt::logout,
        crate::domains::auth::routes::session_mgmt::me,
        crate::domains::auth::routes::session_mgmt::me_export,
        crate::domains::auth::routes::session_mgmt::me_export_download,
        crate::domains::auth::routes::session_mgmt::revoke_all_other_sessions,
        crate::domains::auth::routes::session_mgmt::revoke_session,
        crate::domains::auth::routes::session_mgmt::step_up,
        crate::domains::auth::routes::session_mgmt::switch_workspace,
        crate::domains::auth::routes::mfa::list_mfa_factors,
        crate::domains::auth::routes::mfa::begin_totp_enrollment,
        crate::domains::auth::routes::mfa::confirm_totp_enrollment,
        crate::domains::auth::routes::mfa::webauthn_auth_start,
        crate::domains::auth::routes::mfa::begin_webauthn_enrollment,
        crate::domains::auth::routes::mfa::confirm_webauthn_enrollment,
        crate::domains::auth::routes::mfa::generate_recovery_codes,
        crate::domains::auth::routes::mfa::remove_mfa_factor,
        crate::domains::auth::routes::password::approve_recovery,
        crate::domains::auth::routes::password::forgot_password,
        crate::domains::auth::routes::password::reset_password,
        crate::domains::auth::jwks::get_jwks,
        crate::domains::billing::routes::manage::get_billing_overview,
        crate::domains::billing::routes::manage::create_checkout,
        crate::domains::billing::routes::manage::create_portal,
        crate::domains::billing::routes::manage::get_billing_usage,
        crate::domains::billing::routes::manage::get_entitlements,
        crate::domains::billing::routes::webhooks::handle_stripe_webhook,
        crate::domains::members::routes::manage::list_members,
        crate::domains::members::routes::manage::update_member,
        crate::domains::members::routes::manage::remove_member,
        crate::domains::members::routes::invitations::invite_member,
        crate::domains::members::routes::invitations::accept_invitation,
        crate::domains::workspaces::routes::manage::list_workspaces,
        crate::domains::workspaces::routes::manage::create_workspace,
        crate::domains::workspaces::routes::manage::get_workspace,
        crate::domains::workspaces::routes::manage::update_workspace,
        crate::domains::security::routes::list_security_events,
        crate::domains::security::routes::export_security_events,
        crate::domains::security::routes::list_recovery_reviews,
        crate::domains::security::routes::worker_queue_status,
        crate::domains::authz::routes::decide,
        crate::domains::developer::routes::me,
        crate::domains::developer::apps_routes::list_apps,
        crate::domains::developer::apps_routes::create_app,
        crate::domains::developer::apps_routes::get_app,
        crate::domains::developer::apps_routes::update_redirects,
        crate::domains::developer::apps_routes::revoke_app,
        crate::domains::developer::webhooks_routes::list_webhooks,
        crate::domains::developer::webhooks_routes::create_webhook,
        crate::domains::developer::webhooks_routes::delete_webhook,
        crate::domains::developer::tokens_routes::inspect_token,
        crate::domains::developer::tokens_routes::exchange_playground_code,
        crate::domains::developer::logs_routes::list_logs,
        crate::domains::legal::routes::grant_consent,
        crate::domains::legal::routes::list_consents,
        crate::domains::legal::routes::revoke_consent,
        crate::domains::federation::routes::domains::list_domains,
        crate::domains::federation::routes::domains::create_domain,
        crate::domains::federation::routes::domains::update_domain,
        crate::domains::federation::routes::domains::verify_domain,
        crate::domains::federation::routes::domains::delete_domain,
        crate::domains::federation::routes::idp::list_identity_providers,
        crate::domains::federation::routes::idp::create_identity_provider,
        crate::domains::federation::routes::idp::update_identity_provider,
        crate::domains::federation::routes::idp::delete_identity_provider,
        crate::domains::federation::routes::idp::oidc_discovery,
        crate::domains::federation::routes::idp::saml_metadata,
        crate::domains::federation::routes::protocol::oidc_callback,
        crate::domains::federation::routes::protocol::saml_acs,
        crate::domains::federation::routes::scim::list_scim_connectors,
        crate::domains::federation::routes::scim::create_scim_connector,
        crate::domains::federation::routes::scim::update_scim_connector,
        crate::domains::federation::routes::scim::delete_scim_connector,
        crate::domains::federation::routes::identities::list_linked_identities,
        crate::domains::federation::routes::identities::link_identity,
        crate::domains::federation::routes::identities::unlink_identity,
        crate::domains::federation::routes::identities::jit_provision,
        crate::domains::oauth::routes::authorize::authorize,
        crate::domains::oauth::metadata::oauth_authorization_server_metadata,
        crate::domains::oauth::metadata::openid_configuration,
        crate::domains::oauth::routes::token::token,
        crate::domains::oauth::routes::userinfo::userinfo,
        crate::domains::oauth::routes::introspect::introspect,
        crate::domains::oauth::routes::revoke::revoke,
        crate::domains::oauth::routes::clients::list_clients,
        crate::domains::oauth::routes::clients::create_client,
        crate::domains::oauth::routes::clients::revoke_client,
        crate::domains::oauth::routes::clients::list_client_policies,
        crate::domains::oauth::routes::clients::create_client_policy,
        crate::domains::oauth::routes::clients::update_client_policy,
        crate::domains::oauth::routes::clients::delete_client_policy,
        crate::domains::oauth::routes::device::device_authorize,
        crate::domains::oauth::routes::device::device_verify,
        crate::domains::oauth::routes::device::device_approve,
        crate::domains::oauth::routes::device::device_deny,
        crate::http::well_known::change_password_well_known,
        crate::http::well_known::gpc_well_known,
        crate::http::well_known::passkey_endpoints_well_known,
        crate::http::well_known::webauthn_well_known,
        crate::domains::service_accounts::routes::manage::list_service_accounts,
        crate::domains::service_accounts::routes::manage::create_service_account,
        crate::domains::service_accounts::routes::manage::get_service_account,
        crate::domains::service_accounts::routes::manage::update_service_account,
        crate::domains::service_accounts::routes::state::suspend_service_account,
        crate::domains::service_accounts::routes::state::reactivate_service_account,
        crate::domains::service_accounts::routes::oauth_clients::create_oauth_client,
        crate::domains::service_accounts::routes::oauth_clients::attach_oauth_client,
        crate::domains::service_accounts::routes::oauth_clients::rotate_oauth_client_secret,
        crate::domains::service_accounts::routes::oauth_clients::revoke_oauth_client,
    ),
)]
pub struct IdentityApiDoc;

pub fn openapi_routes() -> axum::Router<crate::app::AppState> {
    SwaggerUi::new("/docs")
        .url("/api/openapi.json", IdentityApiDoc::openapi())
        .into()
}
