#[path = "identity.domains.workspaces.core.rs"]
pub mod core;
#[path = "identity.domains.workspaces.db.rs"]
pub mod db;
#[path = "identity.domains.workspaces.policy.rs"]
pub mod policy;
#[path = "identity.domains.workspaces.routes.rs"]
pub mod routes;
#[path = "identity.domains.workspaces.service.rs"]
pub mod service;
#[path = "identity.domains.workspaces.settings.rs"]
pub mod settings;
#[path = "identity.domains.workspaces.types.rs"]
pub mod types;
#[path = "identity.domains.workspaces.validation.rs"]
pub mod validation;
