[package]
name = "nvbes-email"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait = "0.1"
lettre.workspace = true
reqwest.workspace = true
nvbes-core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
