[package]
name = "nvbes-redis"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
redis = { version = "1.6", features = ["tokio-comp", "json", "streams", "script"] }
bb8-redis = "0.26"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
metrics.workspace = true
chrono.workspace = true
uuid.workspace = true

[dev-dependencies]
nvbes-test-utils = { path = "../test-utils" }
