[package]
name = "nvbes-enterprise-service"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
nvbes-core = { path = "../../libs/rust/core" }
nvbes-observability = { path = "../../libs/rust/observability", features = ["otlp", "profiling"] }
prost = "0.14.4"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-prost = "0.14.6"
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["json"] }
uuid.workspace = true

[build-dependencies]
protoc-bin-vendored = "3.2.0"
tonic-prost-build = "0.14.6"
