[package]
name = "nvbes-storage"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait = "0.1"
aws-config = { version = "=1.8.16", default-features = false, features = ["rt-tokio", "credentials-process", "sso", "default-https-client"] }
aws-sdk-s3 = { version = "=1.137.0", default-features = false, features = ["sigv4a", "http-1x", "default-https-client", "rt-tokio"] }
aes-gcm.workspace = true
base64.workspace = true
hkdf.workspace = true
nvbes-core = { path = "../core" }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url = "2"
