[package]
name = "nvbes-identity-worker"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
nvbes-email = { path = "../../libs/rust/email" }
nvbes-core = { path = "../../libs/rust/core" }
nvbes-redis = { path = "../../libs/rust/redis" }
nvbes-identity-api = { path = "../identity-api" }
nvbes-observability = { path = "../../libs/rust/observability", features = ["otlp", "profiling"] }
nvbes-product-analytics = { path = "../../libs/rust/product-analytics" }
nvbes-region = { path = "../../libs/rust/region" }
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
