[package]
name = "nvbes-identity-worker"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
hex.workspace = true
nvbes-email = { path = "../../libs/rust/email" }
nvbes-core = { path = "../../libs/rust/core" }
nvbes-storage = { path = "../../libs/rust/storage" }
nvbes-redis = { path = "../../libs/rust/redis" }
nvbes-observability = { path = "../../libs/rust/observability", features = ["otlp", "profiling"] }
nvbes-product-identity = { path = "../../libs/rust/products/identity" }
nvbes-product-analytics = { path = "../../libs/rust/product-analytics" }
nvbes-region = { path = "../../libs/rust/region" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
tokio.workspace = true
tonic = { workspace = true, features = ["tls-webpki-roots"] }
tonic-prost = "0.14.6"
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["json"] }
uuid.workspace = true
prost = "0.14.4"

[build-dependencies]
protoc-bin-vendored = "3.2.0"
tonic-prost-build = "0.14.6"

[dev-dependencies]
async-trait = "0.1"
prost-types = "0.14"
redis = { version = "0.29", features = ["tokio-comp"] }
