#!/usr/bin/env node
import { existsSync, readFileSync } from 'node:fs';

const errors = [];

function read(path) {
  if (!existsSync(path)) {
    errors.push(`${path}: missing`);
    return '';
  }
  return readFileSync(path, 'utf8');
}

function readJson(path) {
  const content = read(path);
  if (!content) return undefined;
  try {
    return JSON.parse(content);
  } catch (error) {
    errors.push(`${path}: invalid JSON: ${error.message}`);
    return undefined;
  }
}

function requireIncludes(path, text) {
  const content = read(path);
  if (content && !content.includes(text)) errors.push(`${path}: missing ${text}`);
}

const corePackage = readJson('libs/ts/identity-sdk-core/package.json');
if (!corePackage?.scripts?.['generate:ts'])
  errors.push('libs/ts/identity-sdk-core/package.json: missing generate:ts');
if (!corePackage?.scripts?.['generate:rust'])
  errors.push('libs/ts/identity-sdk-core/package.json: missing generate:rust');

requireIncludes(
  'libs/ts/identity-sdk-core/src/types.gen.ts',
  'auto-generated by openapi-typescript',
);
requireIncludes('contracts/protobuf/nvbes/platform/v1/common.proto', 'syntax = "proto3";');
requireIncludes('contracts/protobuf/nvbes/email/v1/email.proto', 'service EmailDeliveryService');
requireIncludes(
  'contracts/protobuf/nvbes/trust_risk/v1/trust_risk.proto',
  'service TrustRiskSignalService',
);
requireIncludes('contracts/events/manifest.json', 'account.profile.created');
requireIncludes('contracts/events/manifest.json', 'billing.entitlement.changed');

if (errors.length > 0) {
  console.error('Codegen coverage checks failed:');
  for (const error of errors) console.error(`- ${error}`);
  process.exit(1);
}

console.log('Codegen coverage: ok');
