#!/usr/bin/env node
import { existsSync, readFileSync } from 'node:fs';

const errors = [];

function read(path) {
  if (!existsSync(path)) {
    errors.push(`${path}: missing`);
    return '';
  }
  return readFileSync(path, 'utf8');
}

function readJson(path) {
  const content = read(path);
  if (!content) return undefined;
  try {
    return JSON.parse(content);
  } catch (error) {
    errors.push(`${path}: invalid JSON: ${error.message}`);
    return undefined;
  }
}

function requireIncludes(path, text) {
  const content = read(path);
  if (content && !content.includes(text)) errors.push(`${path}: missing ${text}`);
}

const openapiManifest = readJson('contracts/openapi/manifest.json');
if (!Array.isArray(openapiManifest?.apis) || openapiManifest.apis.length === 0) {
  errors.push('contracts/openapi/manifest.json: apis must be non-empty');
}

const corePackage = readJson('libs/ts/identity-sdk-core/package.json');
if (!corePackage?.scripts?.['generate:ts'])
  errors.push('libs/ts/identity-sdk-core/package.json: missing generate:ts');
if (!corePackage?.scripts?.['generate:rust'])
  errors.push('libs/ts/identity-sdk-core/package.json: missing generate:rust');
if (!corePackage?.scripts?.['generate:go'])
  errors.push('libs/ts/identity-sdk-core/package.json: missing generate:go');

const backofficeServicePackage = readJson('libs/ts/backoffice-service-sdk-core/package.json');
if (!backofficeServicePackage?.scripts?.['generate:ts'])
  errors.push('libs/ts/backoffice-service-sdk-core/package.json: missing generate:ts');

requireIncludes(
  'libs/ts/identity-sdk-core/src/types.gen.ts',
  'auto-generated by openapi-typescript',
);
requireIncludes(
  'libs/ts/backoffice-service-sdk-core/src/types.gen.ts',
  'auto-generated by openapi-typescript',
);
requireIncludes('apps/backoffice-service/openapi.json', 'nvbes Backoffice API');
requireIncludes('libs/ts/backoffice-service-sdk-core/openapi.json', 'nvbes Backoffice API');
requireIncludes('libs/rust/identity-sdk-backend/src/lib.rs', 'pub use client::IdentityClient;');
requireIncludes('libs/go/identity-sdk/sdk.go', 'package identitysdk');
requireIncludes('contracts/protobuf/nvbes/platform/v1/common.proto', 'syntax = "proto3";');
requireIncludes('contracts/protobuf/nvbes/account/v1/account.proto', 'service AccountService');
requireIncludes('contracts/protobuf/nvbes/cloud/v1/cloud.proto', 'service CloudService');
requireIncludes('contracts/protobuf/nvbes/developer/v1/developer.proto', 'service DeveloperService');
requireIncludes('contracts/protobuf/nvbes/enterprise/v1/enterprise.proto', 'service EnterpriseService');
requireIncludes('contracts/protobuf/nvbes/billing/v1/billing.proto', 'RecordLedgerEntry');
requireIncludes('contracts/events/manifest.json', 'identity.user.created');
requireIncludes('contracts/events/manifest.json', 'account.user.created');
requireIncludes('contracts/events/manifest.json', 'cloud.workspace.created');
requireIncludes('contracts/events/manifest.json', 'developer.app.created');
requireIncludes('contracts/events/manifest.json', 'enterprise.policy.changed');
requireIncludes('contracts/openapi/manifest.json', '"surface": "account"');
requireIncludes('contracts/openapi/manifest.json', '"name": "cloud-public-v1"');
requireIncludes('contracts/openapi/manifest.json', 'docs/api/openapi/cloud-public-v1.openapi.json');
requireIncludes('docs/api/openapi/cloud-public-v1.openapi.json', 'nvbes Cloud API');
requireIncludes('docs/api/openapi/cloud-public-v1.openapi.json', 'https://cloud.nvbes.fr');

if (errors.length > 0) {
  console.error('Codegen coverage checks failed:');
  for (const error of errors) console.error(`- ${error}`);
  process.exit(1);
}

console.log('Codegen coverage: ok');
