import type { DriveWorkspaceState } from './drive.workspace.types';

export function createInitialDriveWorkspace(): DriveWorkspaceState {
  return {
    activeModuleId: 'drive',
    activeSectionId: 'files',
    currentFolderId: 'folder-clients',
    query: '',
    viewMode: 'list',
    sort: 'updated',
    selectedEntryIds: [],
    detailsSelection: null,
    entries: [
      {
        id: 'folder-clients',
        parentId: null,
        name: 'Clients',
        kind: 'folder',
        status: 'active',
        shareStatus: 'private',
        sizeBytes: 0,
        ownerId: 'member-owner',
        createdAt: '2026-05-03T08:00:00.000Z',
        updatedAt: '2026-06-07T14:30:00.000Z',
        starred: true,
        sharedWithCount: 0,
      },
      {
        id: 'file-brief',
        parentId: 'folder-clients',
        name: 'Brief refonte client.pdf',
        kind: 'document',
        status: 'active',
        shareStatus: 'shared',
        sizeBytes: 2_413_568,
        ownerId: 'member-owner',
        createdAt: '2026-05-20T09:15:00.000Z',
        updatedAt: '2026-06-07T16:45:00.000Z',
        mimeType: 'application/pdf',
        starred: false,
        sharedWithCount: 3,
      },
      {
        id: 'file-contract',
        parentId: 'folder-clients',
        name: 'Contrat prestation.docx',
        kind: 'document',
        status: 'active',
        shareStatus: 'private',
        sizeBytes: 891_904,
        ownerId: 'member-maya',
        createdAt: '2026-05-28T11:20:00.000Z',
        updatedAt: '2026-06-05T10:10:00.000Z',
        mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        starred: false,
        sharedWithCount: 0,
      },
      {
        id: 'file-archive',
        parentId: 'folder-clients',
        name: 'Archive campagne Q1.zip',
        kind: 'archive',
        status: 'trashed',
        shareStatus: 'private',
        sizeBytes: 18_204_672,
        ownerId: 'member-owner',
        createdAt: '2026-02-14T15:35:00.000Z',
        updatedAt: '2026-06-01T12:00:00.000Z',
        mimeType: 'application/zip',
        starred: false,
        sharedWithCount: 0,
      },
    ],
    shareLinks: [
      {
        id: 'link-brief',
        entryId: 'file-brief',
        token: 'drv_brief_refonte_client',
        label: 'Lien client brief refonte',
        status: 'shared',
        permission: 'view',
        createdAt: '2026-06-02T08:30:00.000Z',
        expiresAt: '2026-07-02T08:30:00.000Z',
        accessCount: 12,
        lastAccessedAt: '2026-06-07T09:05:00.000Z',
      },
    ],
    members: [
      {
        id: 'member-owner',
        name: 'Camille Martin',
        email: 'camille@studio.test',
        role: 'owner',
        status: 'active',
        joinedAt: '2026-01-15T09:00:00.000Z',
        invitedAt: null,
      },
      {
        id: 'member-maya',
        name: 'Maya Chen',
        email: 'maya@studio.test',
        role: 'member',
        status: 'active',
        joinedAt: '2026-03-12T14:00:00.000Z',
        invitedAt: '2026-03-11T10:00:00.000Z',
      },
    ],
    securityEvents: [
      {
        id: 'event-login-maya',
        actorId: 'member-maya',
        action: 'Connexion depuis Paris',
        target: 'Espace Drive',
        severity: 'info',
        createdAt: '2026-06-07T08:25:00.000Z',
      },
      {
        id: 'event-link-brief',
        actorId: 'member-owner',
        action: 'Lien partage cree',
        target: 'Brief refonte client.pdf',
        severity: 'warning',
        createdAt: '2026-06-02T08:30:00.000Z',
      },
    ],
    billing: {
      plan: 'team',
      status: 'active',
      seatsUsed: 2,
      seatsIncluded: 8,
      storageUsedBytes: 42_949_672_960,
      storageLimitBytes: 536_870_912_000,
      renewalDate: '2026-07-15',
    },
    apiKeys: [
      {
        id: 'key-production',
        label: 'Production sync',
        prefix: 'nvb_live_7Kq2',
        status: 'active',
        createdAt: '2026-04-18T13:45:00.000Z',
        lastUsedAt: '2026-06-07T18:20:00.000Z',
        revokedAt: null,
      },
    ],
    toast: null,
  };
}
