[package]
name = "nvbes-cloud-worker"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
nvbes-core = { path = "../../libs/rust/core" }
nvbes-redis = { path = "../../libs/rust/redis" }
redis = { version = "1.6", features = ["tokio-comp"] }
futures-util = "0.3"
nvbes-observability = { path = "../../libs/rust/observability", features = ["otlp", "profiling"] }
nvbes-product-cloud = { path = "../../libs/rust/products/cloud" }
nvbes-region = { path = "../../libs/rust/region" }
nvbes-storage = { path = "../../libs/rust/storage" }
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
