services:
  github-runner-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nvbes-github-runner-1
    restart: unless-stopped
    environment:
      GITHUB_REPOSITORY_URL: https://github.com/nvbes-org/nvbes
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_LABELS: self-hosted,linux,ARM64,docker,macOS
      CARGO_BUILD_JOBS: "6"
      CARGO_TERM_COLOR: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - pnpm-store:/home/runner/.local/share/pnpm/store

  github-runner-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nvbes-github-runner-2
    restart: unless-stopped
    environment:
      GITHUB_REPOSITORY_URL: https://github.com/nvbes-org/nvbes
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_LABELS: self-hosted,linux,ARM64,docker,macOS
      CARGO_BUILD_JOBS: "6"
      CARGO_TERM_COLOR: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - pnpm-store:/home/runner/.local/share/pnpm/store

  github-runner-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nvbes-github-runner-3
    restart: unless-stopped
    environment:
      GITHUB_REPOSITORY_URL: https://github.com/nvbes-org/nvbes
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_LABELS: self-hosted,linux,ARM64,docker,macOS
      CARGO_BUILD_JOBS: "6"
      CARGO_TERM_COLOR: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - pnpm-store:/home/runner/.local/share/pnpm/store

volumes:
  cargo-registry:
  cargo-git:
  pnpm-store:
