import {
  WorkspaceServiceAccountsAttachDialogs,
  WorkspaceServiceAccountsCreateDialogs,
  WorkspaceServiceAccountsOAuthDialogs,
} from './WorkspaceServiceAccountsDialogs.groups';
import type { WorkspaceServiceAccountsDialogsProps } from './WorkspaceServiceAccountsDialogs.types';

export function WorkspaceServiceAccountsDialogs({
  createOpen,
  setCreateOpen,
  createName,
  setCreateName,
  createDescription,
  setCreateDescription,
  createRole,
  setCreateRole,
  createError,
  busyAction,
  onCreate,
  onClearCreate,
  clientDialogOpen,
  setClientDialogOpen,
  clientName,
  setClientName,
  clientScopes,
  setClientScopes,
  clientAudiences,
  setClientAudiences,
  clientResources,
  setClientResources,
  clientRequiredAcr,
  setClientRequiredAcr,
  clientAssertionRequired,
  setClientAssertionRequired,
  clientAssertionJwk,
  setClientAssertionJwk,
  clientError,
  onCreateClient,
  onClearClient,
  attachDialogOpen,
  setAttachDialogOpen,
  attachClientId,
  setAttachClientId,
  attachError,
  onAttachClient,
  onClearAttach,
  secretResult,
  secretDialogOpen,
  setSecretDialogOpen,
}: WorkspaceServiceAccountsDialogsProps) {
  return (
    <>
      <WorkspaceServiceAccountsCreateDialogs
        createOpen={createOpen}
        setCreateOpen={setCreateOpen}
        createName={createName}
        setCreateName={setCreateName}
        createDescription={createDescription}
        setCreateDescription={setCreateDescription}
        createRole={createRole}
        setCreateRole={setCreateRole}
        createError={createError}
        busyAction={busyAction}
        onCreate={onCreate}
        onClearCreate={onClearCreate}
      />

      <WorkspaceServiceAccountsOAuthDialogs
        clientDialogOpen={clientDialogOpen}
        setClientDialogOpen={setClientDialogOpen}
        clientName={clientName}
        setClientName={setClientName}
        clientScopes={clientScopes}
        setClientScopes={setClientScopes}
        clientAudiences={clientAudiences}
        setClientAudiences={setClientAudiences}
        clientResources={clientResources}
        setClientResources={setClientResources}
        clientRequiredAcr={clientRequiredAcr}
        setClientRequiredAcr={setClientRequiredAcr}
        clientAssertionRequired={clientAssertionRequired}
        setClientAssertionRequired={setClientAssertionRequired}
        clientAssertionJwk={clientAssertionJwk}
        setClientAssertionJwk={setClientAssertionJwk}
        clientError={clientError}
        busyAction={busyAction}
        onCreateClient={onCreateClient}
        onClearClient={onClearClient}
      />

      <WorkspaceServiceAccountsAttachDialogs
        attachDialogOpen={attachDialogOpen}
        setAttachDialogOpen={setAttachDialogOpen}
        attachClientId={attachClientId}
        setAttachClientId={setAttachClientId}
        attachError={attachError}
        busyAction={busyAction}
        onAttachClient={onAttachClient}
        onClearAttach={onClearAttach}
        secretResult={secretResult}
        secretDialogOpen={secretDialogOpen}
        setSecretDialogOpen={setSecretDialogOpen}
      />
    </>
  );
}
