export type WorkspaceServiceAccountsClientDialogModel = {
  clientDialogOpen: boolean;
  setClientDialogOpen: (open: boolean) => void;
  clientName: string;
  setClientName: (value: string) => void;
  clientScopes: string;
  setClientScopes: (value: string) => void;
  clientAudiences: string;
  setClientAudiences: (value: string) => void;
  clientResources: string;
  setClientResources: (value: string) => void;
  clientRequiredAcr: string;
  setClientRequiredAcr: (value: string) => void;
  clientAssertionRequired: boolean;
  setClientAssertionRequired: (value: boolean) => void;
  clientAssertionJwk: string;
  setClientAssertionJwk: (value: string) => void;
  clientError: string | null;
  busyAction: string | null;
  onCreateClient: () => void;
  onClearClient: () => void;
};
