import type { WorkspaceServiceAccountsPageModel } from './WorkspaceServiceAccountsPage.types';

export type WorkspaceServiceAccountsDialogsSectionProps = Pick<
  WorkspaceServiceAccountsPageModel,
  | 'createOpen'
  | 'setCreateOpen'
  | 'createName'
  | 'setCreateName'
  | 'createDescription'
  | 'setCreateDescription'
  | 'createRole'
  | 'setCreateRole'
  | 'createError'
  | 'busyAction'
  | 'clearCreate'
  | 'handleCreateServiceAccount'
  | 'clientDialogOpen'
  | 'setClientDialogOpen'
  | 'clientName'
  | 'setClientName'
  | 'clientScopes'
  | 'setClientScopes'
  | 'clientAudiences'
  | 'setClientAudiences'
  | 'clientResources'
  | 'setClientResources'
  | 'clientRequiredAcr'
  | 'setClientRequiredAcr'
  | 'clientAssertionRequired'
  | 'setClientAssertionRequired'
  | 'clientAssertionJwk'
  | 'setClientAssertionJwk'
  | 'clientError'
  | 'handleCreateClient'
  | 'clearClient'
  | 'attachDialogOpen'
  | 'setAttachDialogOpen'
  | 'attachClientId'
  | 'setAttachClientId'
  | 'attachError'
  | 'handleAttachClient'
  | 'clearAttach'
  | 'secretResult'
  | 'secretDialogOpen'
  | 'setSecretDialogOpen'
>;
