import type { WorkspaceServiceAccountsDialogsProps } from './WorkspaceServiceAccountsDialogs.types';
import type { WorkspaceServiceAccountsDialogsSectionProps } from './WorkspaceServiceAccountsPage.dialogs.types';

export function getWorkspaceServiceAccountsDialogsProps(
  props: WorkspaceServiceAccountsDialogsSectionProps,
): WorkspaceServiceAccountsDialogsProps {
  return {
    createOpen: props.createOpen,
    setCreateOpen: props.setCreateOpen,
    createName: props.createName,
    setCreateName: props.setCreateName,
    createDescription: props.createDescription,
    setCreateDescription: props.setCreateDescription,
    createRole: props.createRole,
    setCreateRole: props.setCreateRole,
    createError: props.createError,
    busyAction: props.busyAction,
    onCreate: () => void props.handleCreateServiceAccount(),
    onClearCreate: props.clearCreate,
    clientDialogOpen: props.clientDialogOpen,
    setClientDialogOpen: props.setClientDialogOpen,
    clientName: props.clientName,
    setClientName: props.setClientName,
    clientScopes: props.clientScopes,
    setClientScopes: props.setClientScopes,
    clientAudiences: props.clientAudiences,
    setClientAudiences: props.setClientAudiences,
    clientResources: props.clientResources,
    setClientResources: props.setClientResources,
    clientRequiredAcr: props.clientRequiredAcr,
    setClientRequiredAcr: props.setClientRequiredAcr,
    clientAssertionRequired: props.clientAssertionRequired,
    setClientAssertionRequired: props.setClientAssertionRequired,
    clientAssertionJwk: props.clientAssertionJwk,
    setClientAssertionJwk: props.setClientAssertionJwk,
    clientError: props.clientError,
    onCreateClient: () => void props.handleCreateClient(),
    onClearClient: props.clearClient,
    attachDialogOpen: props.attachDialogOpen,
    setAttachDialogOpen: props.setAttachDialogOpen,
    attachClientId: props.attachClientId,
    setAttachClientId: props.setAttachClientId,
    attachError: props.attachError,
    onAttachClient: () => void props.handleAttachClient(),
    onClearAttach: props.clearAttach,
    secretResult: props.secretResult,
    secretDialogOpen: props.secretDialogOpen,
    setSecretDialogOpen: props.setSecretDialogOpen,
  };
}
