[package]
name = "nvbes-region"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
chrono.workspace = true
csv.workspace = true
ipnet.workspace = true
metrics.workspace = true
prost.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true
zip.workspace = true

[dev-dependencies]
proptest.workspace = true
