[package]
name = "nvbes-observability"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
nvbes-core = { path = "../core" }
sentry.workspace = true
serde.workspace = true
serde_json.workspace = true
tonic.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["json"] }
uuid.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
opentelemetry = { workspace = true, optional = true }
opentelemetry_sdk = { workspace = true, optional = true }
opentelemetry-otlp = { workspace = true, optional = true, features = ["http-proto", "reqwest-rustls"] }
pyroscope = { workspace = true, optional = true }
tracing-opentelemetry = { workspace = true, optional = true }

[features]
otlp = ["dep:opentelemetry", "dep:opentelemetry_sdk", "dep:opentelemetry-otlp", "dep:tracing-opentelemetry"]
profiling = ["dep:pyroscope"]

[dev-dependencies]
tower = "0.5"
