global:
  imageRegistry: ghcr.io/nvbes
  imageTag: "0.1.0"

accountService:
  enabled: true
  image:
    repository: nvbes-account-service

cloudService:
  enabled: true
  image:
    repository: nvbes-cloud-service

accountWeb:
  enabled: true
  image:
    repository: nvbes-account-web

cloudWeb:
  enabled: true
  image:
    repository: nvbes-cloud-web
