[package]
name = "nvbes-developer-service"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
hmac.workspace = true
hex.workspace = true
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
nvbes-core = { path = "../../libs/rust/core" }
nvbes-observability = { path = "../../libs/rust/observability", features = ["otlp", "profiling"] }
nvbes-product-account = { path = "../../libs/rust/products/account" }
prost = "0.14.4"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-prost = "0.14.6"
tower-http = { workspace = true, features = ["request-id", "trace"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["json"] }
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
url = "2.5"
urlencoding.workspace = true
uuid.workspace = true

[build-dependencies]
protoc-bin-vendored = "3.2.0"
tonic-prost-build = "0.14.6"
