services:
  account-service:
    image: ghcr.io/nvbes/nvbes-account-service:0.1.0
  cloud-service:
    image: ghcr.io/nvbes/nvbes-cloud-service:0.1.0
  account-web:
    image: ghcr.io/nvbes/nvbes-account-web:0.1.0
  cloud-web:
    image: ghcr.io/nvbes/nvbes-cloud-web:0.1.0
