[package]
name = "nvbes-account-worker"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "nvbes-account-worker"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
nvbes-storage = { path = "../../libs/rust/storage" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url = "2.5"
uuid.workspace = true
